### PR TITLE
Fix BREAD Validation issues #1963 and #2179

### LINKED ISSUE #1963: Validation scroll to first error not work
- Laravel Version: 5.5.14
- Voyager Version: 1.0.5
- PHP Version:7.1

### Description:
Validation scroll to first error not work if input file type image multiple  / select_dropdown multiple because name have [] like  name="age[]" 
//Scroll to first error
                                        if (Object.keys(d.errors).indexOf(key) === 0) {
                                            $('html, body').animate({
                                                scrollTop: $("[name='"+key+"']").parent().offset().top
                                                        - $('nav.navbar').height() + 'px'
                                            }, 'fast');
                                        }

### Steps To Reproduce:
f

### LINKED ISSUE #2179: Validation fails when display name and field name of a BREAD field don't match
- Laravel Version: 5.5.*
- Voyager Version: 1.0.7
- PHP Version: 7.1.*
- Database Driver & Version: N/A

### Description:

On editing a BREAD resource, when using different field display name and field name, validation rules don't apply and get errors on fields where the conditions are met.

### Steps To Reproduce:

1. Fresh Voyager Install
2. Create a minimum table using Database Administration, with 'id' and 'sometext' fields.
3. Add BREAD to the resource
4. On the display label for 'sometext' field, set something different from 'sometext', like 'texto' and save
5. Create a new resource and set a value for the field 'sometext' labelled 'texto'
6. Press submit. No error will be shown, and there will be javascript errors because can't find the field with selector "[name=texto]" (which actually doesn't exist, as the name attribute for the field is 'somefield')

### Related issues: 

#1963 Validation scroll to first error not work

### PR DESCRIPTION
**Pull request by blitux**
Hello maintainers, 

This is a cleaned up version of an PR I've sent before that fixes two BREAD validation issues:

Fixes #1963: Validation scroll to first error not work  
Fixes #2179: Validation fails when display name and field name of a BREAD field don't match

Closes #2612

This uses custom attributes to show `$field->display_name` on validation error messages, and that's why I'm reverting #2077.

I hope this will be included in the next release as, currently, BREAD form validation is broken when `display_name` and `field_name` don't match.

Thank you in advance.

### CODE REVIEW

**Comment by fletch3555** [comment]
Looks like it should be good.  I don't have time to test it, but perhaps @emptynick or @akazorg does.  If one of them say it's good, I'll get this merged in.

Thanks!

**Comment by regiszanandrea** [comment]
Part of this PR is related to PR #2612.

**Comment by fletch3555** [comment]
@regiszanandrea, can you be more specific? Both PRs touch ~20 files, so it's a royal pain to truly compare them.  What part of this is related to #2612?

**Comment by regiszanandrea** [comment]
@fletch3555 This part: "Validation fails when display name and field name of a BREAD field don't match". The only difference is that @blitux use JS. Personally, I think this PR, better, because it resolves two problems. If you accept this PR, you should close the #2612.

**Comment by vblinden** [comment]
This indeed fixes the problem. This also looks good too me @fletch3555.

**Review by fletch3555 — APPROVED** [review]

**Comment by blitux** [comment]
Awesome guys, thank you for your time!

**Comment by blitux** [comment]
@fletch3555 @samtheson The PR [2198](https://github.com/the-control-group/voyager/pull/2198) should also be closed

**Comment by fletch3555** [comment]
Good catch, thanks @blitux

**Comment by gausam** [comment]
@fletch3555 @blitux Hey gents. Sorry was away on a long holiday and then came back to tight work in January. Back to a normal life starting next week. Thanks for all the work on this.

**Comment by fletch3555** [comment]
No problem, welcome back!

**Comment by gausam** [comment]
Thank ye!

**Pull request merged**
