### PR TITLE
Cache check permission 

### PR DESCRIPTION
**Pull request by MrCrayon**
Cache check permission in basePolicy for CACHE_TIME seconds.

This cache last only for few seconds so there is no need to destroy cache after changing permissions or roles, it's mostly useful to avoid repeating the same query to check permission in browse view.

In my testing in voyager with dummy, browse Post, that has 3 actions this PR makes page generation 16% faster.

Of course with server side pagination the difference in time is negligible but noticeable with client side  pagination and many records.

### CODE REVIEW

**Comment by emptynick** [comment]
How did you measure page generation?
I'm getting longer load-times in both debugbar and Chrome inspection tools by a few mills.

**Comment by MrCrayon** [comment]
1. Installed voyager with dummies
2. Removed unique key from posts.slug (just to make next step easier)
3. Duplicated post until reaching 1000 posts
4. Added to AppServiceProvider boot method
```php
config(['timer' => microtime()]);
```
5. Extendend partials/app-footer.blade.php
```blade
@php
    function pageTracker()
    {
        list($usec, $sec) = explode(" ", config('timer'));
        $time_start = (float)$usec + (float)$sec;
        
        list($usec, $sec) = explode(" ", microtime());
        $time_end = (float)$usec + (float)$sec;

        return 'Generated in ' . number_format($time_end - $time_start, 3).'s';
    }
@endphp
<footer class="app-footer">
    <div class="site-footer-right">
        @if (rand(1,100) == 100)
            <i class="voyager-rum-1"></i> {{ __('voyager::theme.footer_copyright2') }}
        @else
            {!! __('voyager::theme.footer_copyright') !!} <a href="http://thecontrolgroup.com" target="_blank">The Control Group</a>
        @endif
        @php $version = Voyager::getVersion(); @endphp
        @if (!empty($version))
            - {{ $version }}
        @endif
        @if(env('APP_DEBUG'))
         - {!! '<b>'.pageTracker().'</b>' !!}
        @endif
    </div>
</footer>
```
(I have that function in helpers.php but for testing works there too)
6. Access posts index page multiple times with and without cache enabled and log it.

I just tried, there is a bit of variance because I didn't close other programs but it's consistently faster with cache enabled.

Schermata da 2019-10-10 10-31-24

This with the three standard permission checks.

**Comment by MrCrayon** [comment]
I had an idea... since we are not caching it for other requests we could just use an array, same as is used for $dataTypes.

```php
    protected static $cache = []; 
 
    protected function checkPermission(User $user, $model, $action)
    {
        $key = "{$user->getTable()}-{$user->id}-can-{$action}-{$model->getTable()}";

        if (!isset(self::$cache[$key])) {
            if (!isset(self::$datatypes[get_class($model)])) {
                $dataType = Voyager::model('DataType');
                self::$datatypes[get_class($model)] = $dataType->where('model_name', get_class($model))->first();
            }

            $dataType = self::$datatypes[get_class($model)];
            self::$cache[$key] = $user->hasPermission($action.'_'.$dataType->name);
        }

        return self::$cache[$key];
    }
```

This way is even quicker
Schermata da 2019-10-10 10-55-23

**Comment by emptynick** [comment]
That looks even better (and a bit simpler)

**Comment by MrCrayon** [comment]
@emptynick there is a problem with tests, with this PR permissions are kept in memory so when we test:
```php
    /**
     * UserDimmer widget isn't displayed without the right permissions.
     */
    public function testUserDimmerWidgetIsNotShownWithoutTheRightPermissions()
    {
        // We must first login and visit the dashboard page.
        $user = \Auth::loginUsingId(1);

        // Remove `browse_users` permission
        $user->role->permissions()->detach(
            $user->role->permissions()->where('key', 'browse_users')->first()
        );
```
Permission is not really removed because it was cached from the previous test, so even if in normal use it's working the test fails.

I think we need a method in BasePolicy to purge cache to be called before any test that involves permissions, something like:
```php
public static function purgeCache()
{
    self::$cache = [];
}
```

Thoughts?

**Comment by fletch3555** [comment]
Is the policy the best place to store this? I feel like we should have a "PermissionCache" service class (or whatever you want to call it), which handles fetching/caching/purging permissions, thus cleaning up the policy significantly.

**Comment by MrCrayon** [comment]
Yes, totally.
I went for the minimum change but I can refactor.

**Comment by MrCrayon** [comment]
I'm not working on this anymore since I completely refactored caching in https://github.com/MrCrayon/voyager/tree/refactor-caching

**Pull request closed without merging**
