### PR TITLE
Fix routes with empty required parameters

### PR DESCRIPTION
**Pull request by MrCrayon**
Next Laravel release will throw an Exception.

### CODE REVIEW

**Comment by vitormicillo** [comment]
Hi Folks, 
I tried to apply this solution based on the suggestion of @MrCrayon but it didn't work: 
` $('#delete_form')[0].action = '{{ route('voyager.menus.item.destroy', ['menu' => $menu->id, 'id' => '__id']) }}'.replace('__id', id);`

**Review by vitormicillo — COMMENTED** [review]
I tried to modify the line below
`<form action="{{ route('voyager.menus.item.destroy', ['menu' => $menu->id, 'id' => '__id']) }}" id="delete_form" method="POST">`
to
`<form action="#" id="delete_form" method="POST">`
but it did not work

**Comment by MrCrayon** [comment]
Wow v6.6.1 is already out.

@victorboissiere "did not work" is too generic, are you getting an error and in that case which error?

**Comment by vitormicillo** [comment]
Sorry mate, 
I updated my composer and Laravel was updated to the latest version and the menu builder stopped working, this is the full error:
`
Missing required parameters for [Route: voyager.menus.item.destroy] [URI: admin/menus/{menu}/item/{id}]. (View: /home/folder/Project/thames/vendor/tcg/voyager/resources/views/menus/builder.blade.php) `

**Comment by MrCrayon** [comment]
OK, but you can't have that error after applying this PR, can you take a screenshot where it shows the line causing the error in `builder.blade.php`?

Like this but showing full line:
Schermata da 2019-11-28 05-41-25

**Comment by vitormicillo** [comment]
image

**Comment by vitormicillo** [comment]
I commented on the old code and inserted the modified line

image

**Comment by vitormicillo** [comment]
Sorted,  @MrCrayon 
I deleted the commented line and it worked, but I'm surprised that the system is reading code even though it's commented.

**Comment by MrCrayon** [comment]
Your comment is in a javascript block not php block, so that php code is still being executed and causing the exception.

**Review by emptynick — APPROVED** [review]

**Pull request merged**
