### PR TITLE
Refactoring the login page to allow template usage

### PR DESCRIPTION
**Pull request by akiyamaSM**
Allow to use the login template in other pages such as Reset password if needed

```
@extends('voyager::auth.master', ['title' => 'Reset Password'])

@section('content')

@endsection
```

### CODE REVIEW

**Comment by akiyamaSM** [comment]
Hello @emptynick Hope it doesn't bother you taking look at this PR

**Comment by emptynick** [comment]
This would be a breaking change.
Why not simply add `@section('...')` and `@show` around the login-container in `login.blade.php` to make it overridable?

**Comment by akiyamaSM** [comment]
Why is a breaking change?
And in my case i have pages where i need to reset the password and I have to change in the title too.

**Comment by emptynick** [comment]
Because other people might have overriden this view as well.
The title could also be just a section/yield

**Comment by akiyamaSM** [comment]
I really think it should be out of the box. But since its a breaking change. Hope it can make to an other major version.

**Comment by emptynick** [comment]
But like I said before, it can be done much more easy with ~3 lines of code.

**Comment by MrCrayon** [comment]
As @emptynick said title could be:
```blade
@yield('title', 'Admin - '.Voyager::setting("admin.title"))
```
That way we can keep compatibility and it's easily overridable.

**Comment by akiyamaSM** [comment]
I really don't see why it shouldn't be part of its core. I believe that reseting password's flow should be a part of the package.

**Comment by MrCrayon** [comment]
I didn't say I'm against this PR, personally I think it makes sense.

I'm only saying that I like more the use of `yield` for title.
But I have to correct myself, that's not a breaking change because right now users either keep the template or replace it completely.

**Comment by akiyamaSM** [comment]
@mrCrayon thanks, Ill make the change about the yield to fit the requirements

**Comment by akiyamaSM** [comment]
Hello @MrCrayon Changes has been made :D

**Comment by akiyamaSM** [comment]
Any ups ?
@MrCrayon 
@emptynick

**Review by MrCrayon — APPROVED** [review]
I'm good with this, now you have to convince @emptynick :grin:

**Comment by akiyamaSM** [comment]
@MrCrayon hahaha thanks.

**Comment by akiyamaSM** [comment]
Hey @emptynick Hope we can get an answer, I have an other PR that I want to submit for a fix.

**Comment by emptynick** [comment]
Always create a sub-branch from 1.4 so you can create multiple PRs at the same time.

**Pull request merged**
