### PR TITLE
fix_escaping_issue_on_selected_attribute_on_dropdown_field - Fixed an…

### PR DESCRIPTION
**Pull request by iugo-robert**
… escaping issue for the selected attribute on dropdown fields

### CODE REVIEW

**Comment by MrCrayon** [comment]
I think we don't need ```{!! !!}``` either.
This should be fixed everywhere, maybe in another PR.

**Comment by fletch3555** [comment]
@MrCrayon is correct, the `{!!` and `!!}` aren't needed at all here.  I'd rather see a comprehensive PR that replaces all instances of this

**Comment by MrCrayon** [comment]
@iugo-robert let us know if you can work on this or I can open another PR.

**Comment by iugo-robert** [comment]
@MrCrayon feel free to open another PR.

**Pull request closed without merging**
