### PR TITLE
Resolve images resize problems (optional set width or height or both)

### LINKED ISSUE #1950: Large Image Uploads Being Scaled
- Laravel Version: 5.4.36
- Voyager Version: 1.0.5
- PHP Version: 7.1.5
- Database Driver & Version:

### Description:

Large images that are uploaded are being scaled to have a width of 1800px. Is it possible to disable this? I am scaling very large images and it is degrading the quality considerably. In my opinion uploaded images should be left *as is*.

I've tried to disable it by setting `width` to null with;

```
{
	"quality": "100%",
	"resize": {
		"width": null,
		"height": null
	},
	"thumbnails": [
		{
			"name": "thumbnail",
			"crop": {
				"width": 200,
				"height": 40
			}
		}
	],
	"display": {
		"width": 6
	}
}
``` 

which doesn't work...

### Steps To Reproduce:

Upload a large image

### PR DESCRIPTION
**Pull request by SaadEddinHassania**
Resolve images resize problems (optional set width or height or both)

user can now use resize as : 
```
{
    "resize": {
        "width": "3100",
        "height": null
    }
}
```

or

``` 
{
    "resize": {
        "width": "3100"
    }
}
```

and resolve some bugs I found it when I used it

Fixes #1950

### CODE REVIEW

**Comment by SaadEddinHassania** [comment]
emptynick

**Comment by SaadEddinHassania** [comment]
@emptynick

**Comment by SaadEddinHassania** [comment]
@marktopper

**Review by marktopper — APPROVED** [review]

**Comment by marktopper** [comment]
What do you think @fletch3555?

**Pull request merged**
