### PR TITLE
English translation fixes

### PR DESCRIPTION
**Pull request by ghost**
Moved English translation for `create_model_table` from lang/en/bread.php to lang/en/database.php and fixed minor translation bug on views/bread/browse.php

### CODE REVIEW

**Review by emptynick — APPROVED** [review]

**Comment by fletch3555** [comment]
I disagree with moving the translation.  That specific key is only used on the BREAD create page.  If you move that one, you'll need to move the `migration` one right above it, which doesn't seem like it fits in the database file.

**Comment by ghost** [comment]
This translation is used by the "Creat New Table" page. If it is not in the database translation then I believe the translation location needs to change on that page

**Comment by emptynick** [comment]
The string he moved (`voyager::database.create_model_table`) is used in the database tool [here](https://github.com/the-control-group/voyager/blob/1.x-dev/resources/views/tools/database/vue-components/database-table-editor.blade.php#L17).
Those are just 2 different things

**Comment by fletch3555** [comment]
Perhaps it should be duplicated then.  If it exists in 2 places with different/unrelated uses, then they should be different keys (potentially with the same value)

**Comment by fletch3555** [comment]
We're just going to ignore my comments here.... @emptynick has shown me the error of my ways.

This looks good to me.

**Review by fletch3555 — APPROVED** [review]

**Pull request merged**
