### PR TITLE
Do not respect global scopes in the bread

### PR DESCRIPTION
**Pull request by iSWORD**
I believe an admin panel should not obey global scopes. This commit will make the VoyagerBreadController discard the filters imposed by global scopes using "withoutGlobalScopes" and "newQueryWithoutScopes".

### CODE REVIEW

**Comment by iSWORD** [comment]
bump.. ?

**Comment by emptynick** [comment]
This is definitely a breaking change as some people may be using global scopes and end up having to rewrite everything to Policies.
At least for `1.0.x`

**Comment by iSWORD** [comment]
Agreed. I should probably add it as an option in the BREAD builder instead.

**Comment by emptynick** [comment]
Make it either a config var, or take a look at #2827
It introduces a new `details` column to Data-Types with which you _could_ implement a var `respect_global_scopes` or so

**Pull request closed without merging**
