### PR TITLE
MySQL error on creating users role_id foreign key

### PR DESCRIPTION
**Pull request by xaviqv**
Laravel Version: 5.4
Voyager Version: 1.1.0

I've got an error when upgrading from 1.0 to 1.1 on this migration. Separating the two table updates makes it work. Sorry but I don't have the mysql error message or screenshot.

Anyone else got that?

### CODE REVIEW

**Comment by felmorphp** [comment]
Some solution for arrive to the end installation with success? Same someone can give me the sql script for the tables to install?

**Comment by xaviqv** [comment]
@felmorphp by executing voyager installation, it does execute the migration files (that are the database updates) included in voyager package, so the only way you can avoid this error is by editing 2017_11_26_013050_add_user_role_relationship.php in voyager migrations folder. You may choose to do two different things in it BEFORE executing Voyager installation:

1. Delete the line "$table->foreign('role_id')->references('id')->on('roles');". After Voyager installation, you will have to create the foreign key manually in your database users table.
2. Replace the migration file original content with what I have posted in here https://github.com/the-control-group/voyager/pull/3076/files

**Comment by FelipeOneHouse** [comment]
Not working yet , i think needed erase this too from create_user_roles_table
$table->foreign('role_id')->references('id')->on('roles')->onDelete('cascade');

**Comment by FelipeOneHouse** [comment]
Equally if i have a table users yet, without column role_id, the sql try update column and not add? this fall in error too

**Comment by FelipeOneHouse** [comment]
I confirm only with the first change is not working , need update the second file too, now is installed ok 👍 Publishing the Voyager assets, database, and config files
Copied Directory [/vendor/tcg/voyager/publishable/assets] To [/public/vendor/tcg/voyager/assets]
Copied Directory [/vendor/tcg/voyager/publishable/database/seeds] To [/database/seeds]
Publishing complete.
Publishing complete.
Migrating the database tables into your application
Migrating: 2016_01_01_000000_add_voyager_user_fields
Migrated:  2016_01_01_000000_add_voyager_user_fields
Migrating: 2016_01_01_000000_create_data_types_table
Migrated:  2016_01_01_000000_create_data_types_table
Migrating: 2016_05_19_173453_create_menu_table
Migrated:  2016_05_19_173453_create_menu_table
Migrating: 2016_10_21_190000_create_roles_table
Migrated:  2016_10_21_190000_create_roles_table
Migrating: 2016_10_21_190000_create_settings_table
Migrated:  2016_10_21_190000_create_settings_table
Migrating: 2016_11_30_135954_create_permission_table
Migrated:  2016_11_30_135954_create_permission_table
Migrating: 2016_11_30_141208_create_permission_role_table
Migrated:  2016_11_30_141208_create_permission_role_table
Migrating: 2016_12_26_201236_data_types__add__server_side
Migrated:  2016_12_26_201236_data_types__add__server_side
Migrating: 2017_01_13_000000_add_route_to_menu_items_table
Migrated:  2017_01_13_000000_add_route_to_menu_items_table
Migrating: 2017_01_14_005015_create_translations_table
Migrated:  2017_01_14_005015_create_translations_table
Migrating: 2017_01_15_000000_make_table_name_nullable_in_permissions_table
Migrated:  2017_01_15_000000_make_table_name_nullable_in_permissions_table
Migrating: 2017_03_06_000000_add_controller_to_data_types_table
Migrated:  2017_03_06_000000_add_controller_to_data_types_table
Migrating: 2017_04_21_000000_add_order_to_data_rows_table
Migrated:  2017_04_21_000000_add_order_to_data_rows_table
Migrating: 2017_07_05_210000_add_policyname_to_data_types_table
Migrated:  2017_07_05_210000_add_policyname_to_data_types_table
Migrating: 2017_08_05_000000_add_group_to_settings_table
Migrated:  2017_08_05_000000_add_group_to_settings_table
Migrating: 2017_11_26_013050_add_user_role_relationship
Migrated:  2017_11_26_013050_add_user_role_relationship
Migrating: 2017_11_26_015000_create_user_roles_table
Migrated:  2017_11_26_015000_create_user_roles_table
Migrating: 2018_03_11_000000_add_user_settings
Migrated:  2018_03_11_000000_add_user_settings
Migrating: 2018_03_14_000000_add_details_to_data_types_table
Migrated:  2018_03_14_000000_add_details_to_data_types_table
Migrating: 2018_03_16_000000_make_settings_value_nullable
Migrated:  2018_03_16_000000_make_settings_value_nullable
Attempting to set Voyager User model as parent to App\User
Dumping the autoloaded files and reloading all new files
Adding Voyager routes to routes/web.php
Seeding data into the database
Copied File [/vendor/tcg/voyager/publishable/config/voyager.php] To [/config/voyager.php]
Publishing complete.
Setting up the hooks
Copied File [/vendor/larapack/hooks/publishable/config/hooks.php] To [/config/hooks.php]
Publishing complete.
Hooks are now ready to use! Go ahead and try to "php artisan hook:install test-hook"
Adding the storage symlink to your public folder
The [public/storage] directory has been linked.
Successfully installed Voyager! Enjoy

**Comment by fletch3555** [comment]
~~Closing as duplicate of #3073~~

**Comment by emptynick** [comment]
Already fixed in https://github.com/the-control-group/voyager/pull/3974

**Pull request closed without merging**
