### PR TITLE
Bugfix #2431 BelongsTo exception

### PR DESCRIPTION
**Pull request by JapSeyz**
This uses the old FIND method as a fallback, and exposes a trait that users can add to their own models

### CODE REVIEW

**Comment by fletch3555** [comment]
Duplicate of #2432.  Not sure I like adding the fallback that way, but it _may_ need to be done to be more user-friendly.  You also only add this for `Role` and `User` models.  Mine added it for the rest as well.

**Comment by JapSeyz** [comment]
Yeah, that fallback seems to be the best thing for now.

I can add it for the rest too. I just don't think they have relationships?

**Comment by JapSeyz** [comment]
Added the trait to the rest of the models

**Comment by tnylea** [comment]
Thanks for this. I was actually going to add a PR for this as well.

@JapSeyz Can you fix the StyleCI recommendations and I can merge this in.

Thanks.

**Comment by JapSeyz** [comment]
@tnylea Should be good to go

**Comment by fletch3555** [comment]
@tnylea, my preference is leaning toward my PR (see link above).  All it needs is the fallback, which I'm not really sure I like (it's more user-friendly, but somewhat hides the caching benefit. I think I'd rather force users to add the trait rather than just hide the error).  Also, this one has the trait added to a few models unnecessarily (e.g. DataRow and DataType)

**Pull request closed without merging**
