### PR TITLE
Allow developers to update tinymce configuration from views

### PR DESCRIPTION
**Pull request by belguinan**
### Allow developers to update tinymce configuration from views

This PR allows developers to update tinymce configurations from @section('javascript').
This is also a fix for [4188](https://github.com/the-control-group/voyager/issues/4188)

#### USE CASE:
Add custom buttons to navbar
In tinymce documentation "[here](https://www.tiny.cloud/docs-4x/advanced/creating-a-custom-button/#basicbutton)"

We can achieve this using the code bellow 

```
window.tinymceConfig.toolbar = window.tinymceConfig.toolbar + ' | currentdate'
window.tinymceConfig.setup = function(editor) {
    function toTimeHtml(date) {
        return '<time datetime="' + date.toString() + '">' + date.toDateString() + '</time>';
    }
    function insertDate() {
        var html = toTimeHtml(new Date());
        editor.insertContent(html);
    }
    editor.addButton('currentdate', {
        icon: 'insertdatetime',
        //image: 'http://p.yusukekamiyamane.com/icons/search/fugue/icons/calendar-blue.png',
        tooltip: "Insert Current Date",
        onclick: insertDate
    });
}
```

### CODE REVIEW

**Comment by fletch3555** [comment]
Don't commit the app.css and app.js files.  They get compiled automatically after we merge the pull request and having them committed causes merge conflicts.  Please undo that change.

**Comment by belguinan** [comment]
@fletch3555 Thank you, done.

**Comment by emptynick** [comment]
Voyager already allows you to manipulate TinyMCE in 2 ways.
Not really sure what the benefit of this is, you can do the same in another way already.

**Comment by belguinan** [comment]
@emptynick 
The reason why i submitted this is. I had a TASK where admin needs a custom button on TinyMCE. 
Voyager gives you 2 callbacks function that you can call and make some changes over the code. BUT you couldn't make any initial changes. So the only solution is to make configuration a global variable and you can make changes in views if you override any needed view.
So This PR gives developer a full control over TinyMCE configuration.

Thank you.

**Comment by emptynick** [comment]
The init-callback is indeed useful to manipulate tinymce when initializing and we have users adding buttons through those two methods.

**Pull request closed without merging**
