### PR TITLE
Fix 'z-index' on search form

### LINKED ISSUE #2699: The search form above the pop-up
- Laravel Version: 5.5.34
- Voyager Version: 1.0.15
- PHP Version: 7.1
- Database Driver & Version: MySQL
- **Browser**: Chrome 63.0.3239.132 (dev, 64bit)
- **System**: Windows 10

### Description:
It is not possible to delete a multiple table rows since the button below the search form.

### PR DESCRIPTION
**Pull request by defaultpage**
Fixes #2699

### CODE REVIEW

**Comment by defaultpage** [comment]
As alternative solution we can change:
```css
.modal-open .select2-container {
  z-index: 999999 !important;
  width: 100% !important;
}
```
to
```css
.modal-open .select2-container {
  z-index: 100000 !important;
  width: 100% !important;
}
```
For any value above 100000, the error appears.

**Comment by vblinden** [comment]
The solution you gave works fine for me and solves the problem.

**Comment by regiszanandrea** [comment]
Worked for me too.

**Review by fletch3555 — APPROVED** [review]

**Comment by xaviqv** [comment]
I got a similar issue but with a customized select2 that I have in the bread buttons panel. With the modal opened, the select2 was appearing on front of it. The alternative shared by @ArtemMolotov works fine for it! Thank you!

**Pull request merged**
