### PR TITLE
Relationship with primary key other than id

### PR DESCRIPTION
**Pull request by andre4nap**
Make relationship with primary key other than field 'id'. Now it's possible to use also a 'slug' as primary string without problems.

### CODE REVIEW

**Comment by andre4nap** [comment]
#4795

**Comment by andre4nap** [comment]
This patch should fix the issue #2648

**Review by JackShev — APPROVED** [review]
great!

**Review by RazorSiM — APPROVED** [review]
Tested and working as for the latest Laravel version

**Comment by emptynick** [comment]
Superseded by https://github.com/the-control-group/voyager/pull/4702

**Pull request closed without merging**
