### PR TITLE
Update voyager_tinymce.js with setup callback

### PR DESCRIPTION
**Pull request by CSchloegel**
This callback allows developers to access the TinyMCE Editor BEFORE it has been instantiated. Useful for adding plugins etc...

### CODE REVIEW

**Review by emptynick — APPROVED** [review]

**Comment by Xmk** [comment]
Where it?
https://github.com/the-control-group/voyager/blob/1.1/resources/assets/js/voyager_tinymce.js

**Comment by emptynick** [comment]
In 1.x because its a breaking change.
https://github.com/the-control-group/voyager/blob/4e5e8c80507b2d5152994ad07da80a626e106958/resources/assets/js/voyager_tinymce.js#L31-L35

**Comment by Xmk** [comment]
I need to autoload the data\blob images on the server, but the Voyager simply does not allow me to do this with human methods!

**Comment by emptynick** [comment]
Switch to 1.x if you need this callback.

**Comment by Xmk** [comment]
@emptynick thanks, I try

**Comment by niels-numbers** [comment]
> Useful for adding plugins etc...

How do you add a plugin with the  setup callback? I couldn't find that in the TinyMCE docs.  Maybe this would be useful to add to the docs aswell.

**Pull request merged**
