### PR TITLE
Let developers use a separate guard for auth users

### PR DESCRIPTION
**Pull request by alkhachatryan**
Most of us doesn't use the same guard (user guard) for both of admins and front users.

I'm not exception. I have two guards - users and admins. And I couldn't use your awesome package because of hardcoded auth guards.

In this PR you can see 12 changed  files, where I decided to separate the front and admin users guards.

### CODE REVIEW

**Comment by emptynick** [comment]
But that guard doesn't exist by default. That's why your tests are failing

**Comment by alkhachatryan** [comment]
So you can add in voyager installation and it will install it automatically

**Comment by emptynick** [comment]
But we can't (technically) and won't merge a faulty PR.

**Comment by emptynick** [comment]
We can't merge your PR as you deleted your fork. Closing.

**Pull request closed without merging**
