### PR TITLE
Feature server side order and search for belongsto field

### LINKED ISSUE #2661: Sort by relationship column
- Laravel Version: 5.5.34
- Voyager Version: 1.0.15
- PHP Version: 7.1.0
- Database Driver & Version: mysql

### Description:
Sorting by relationships, not work for me. Maybe it's because of my changes, but I think I saw the problem after installation too. Can you check if the sorting works for you?

We can see `getRelationships` method where I found next code:
```php
        $relationships = [];

        $dataType->browseRows->each(function ($item) use (&$relationships) {
            $details = json_decode($item->details);
            if (isset($details->relationship) && isset($item->field)) {
                 ...
            }
        });

        return $relationships;
```
But in relationship details:
```
{"model":"App\\Product","table":"products","type":"belongsTo","column":"product_id","key":"id","label":"name","pivot_table":"admins","pivot":"0"}
```

### Steps To Reproduce:
1. Create relationship (https://voyager.readme.io/docs/relationships)
2. Sort table by new relationship

### LINKED ISSUE #3595: BelongsTo ServerSide Search
## Version information

 - Laravel: v5.4
 - Voyager: v1.1.3
 - PHP: 7.1
 - Database: MySQL 5.6.4

## Description
Can't search BelongTo items on Browse view in Server-Side Search

## Steps To Reproduce
1. Go to BREAD
2. Create a new BelongsTo relationship.
3. Select Server-Side pagination
4. Go to the model Browse View
5. Try to search content based on the Related table.

## Expected behavior
What is needed here, is to customize the seach-key dropdown filter, so it is possible to search based on the related model data.

## Screenshots
ss

### PR DESCRIPTION
**Pull request by MrCrayon**
Enable order and search server side for belongsto relationship fields.

~For the search I am applying a global scope, that's the only things that will not require to reimplement pagination manually, for that reason I had to move search checks because globalScope needs to be added as first thing or will not work.~

Added a couple of tests, both using a scope and sofdelete work but we should probably add tests for those too.

Closes #2661 and closes #3595

Supersede #5120

### CODE REVIEW

**Comment by MrCrayon** [comment]
> I have checked your PR on my local environment and sorting was without problem. Searching in via title was also fine but when I tried to search by parent I didn't get anything - just a blank white page

@Stehos thanks again for checking.
I saw you posted on Slack about some unrelated problem, was that connected or search still does not work?
Can you check your logs to see if there is any error?

**Review by Stehos — APPROVED** [review]
@MrCrayon I checked this and both things seems to be working for me without issues. Searching sorting, too.

**Comment by Stehos** [comment]
> > I have checked your PR on my local environment and sorting was without problem. Searching in via title was also fine but when I tried to search by parent I didn't get anything - just a blank white page
> 
> @Stehos thanks again for checking.
> I saw you posted on Slack about some unrelated problem, was that connected or search still does not work?
> Can you check your logs to see if there is any error?

Sorry, I didn't see your comment. The discussion on the slack was not related to this thing. I also approved your last commit and I am not sure but I think this was causing my issues two days ago. Thank you a lot.

**Review by emptynick — APPROVED** [review]

**Comment by muriloferanti** [comment]
This work for me

```
            // Update
            if ($search->value != '' && $search->key && $search->filter) {
                $search_filter = ($search->filter == 'equals') ? '=' : 'LIKE';
                $search_value = ($search->filter == 'equals') ? $search->value : '%'.$search->value.'%';

                $isRelation = false;
                $relationshipIds = [];
                $sortableColumns = $this->getSortableColumns($dataType->browseRows);

                $oldchampson = '';

                $searchField = $dataType->name.'.'.$search->key;

                foreach ($dataType->browseRows as $key => $row) {
                    if ($row->type == 'relationship' && isset($row->details) && $row->details->type == 'belongsTo'){
                        if($search->key == $row->field){
                            $relationshipIds = DB::table($row->details->table)
                                ->select($row->details->key, $row->details->label)
                                ->where($row->details->label, $search_filter, $search_value)
                                ->pluck($row->details->key)
                                ->toArray();
                            $oldchampson = $row->details->column;
                            $isRelation = true;
                        }
                    }
                }
                if($isRelation) {
                    $query->whereIn($oldchampson,$relationshipIds);
                } else {
                    $query->where($searchField, $search_filter, $search_value);
                }
            }
            // Update
```

**Comment by sanvolter** [comment]
For me either

**Comment by theqdev** [comment]
Using @muriloferanti's solution works well, as it fixes `belongsTo` type of relations search filters, while also preserving search fields types when searching/paginating (eg: {String} Username - {Int} User Id).

On top of this, I've used the following snippet to completely disable `hasOne` type of relations, for which I don't have a fix yet, the search still failing for them (but I'm not relying on them too much either now).

```
        if ($dataType->server_side) {
            $searchNames = $dataType->browseRows->filter(function ($formfield) {
                if($formfield->type === 'relationship') {
                    if($formfield->details->type === 'belongsTo'){
                        return true;
                    }
                    else{
                        return false;
                    }
                }
                return true;
            })->mapWithKeys(function ($row) {
                return [$row['field'] => $row->getTranslatedAttribute('display_name')];
            });
        }
```

_Fix similar to the one attempted in here @ https://github.com/thedevdojo/voyager/pull/5312 . _

If we could get a fix for the `hasOne` type of relationships search in a similar manner, I think we could sketch a PR that would close a bunch if not all existing items related to server-side search - I will re-visit this one as well when I get the chance.

**Pull request merged**
