### PR TITLE
fix issue

### PR DESCRIPTION
**Pull request by agoalofalife**
fix issue https://github.com/the-control-group/voyager/issues/3071

### CODE REVIEW

**Review by cyrildewit — COMMENTED** [review]
Simply removing this line is not the right solution. Because we're changing the `role_id` collumn in the `up` method to an unsigned integer, we should also rollback this change in the `down` method. Even when the collumn is dropped in the `2016_01_01_000000_add_voyager_user_fields` migration.

**Comment by cyrildewit** [comment]
A better, but less nice looking solution would be:

```php
Schema::table('users', function (Blueprint $table) {
    $table->dropForeign(['role_id']);
});

Schema::table('users', function (Blueprint $table) {
    $table->integer('role_id')->change();
});
```

I think that @strickdj already posted this solution at #2863.

**Comment by agoalofalife** [comment]
@cyrildewit offer the full version here?
```php

     */
    public function down()
    {
      Schema::table('users', function (Blueprint $table) {
        $table->dropForeign(['role_id']);
      });

     Schema::table('users', function (Blueprint $table) {
       $table->integer('role_id')->change();
     });
    }
```

**Comment by agoalofalife** [comment]
@cyrildewit does it work? 
you tried to roll back?
if Yes I am ready to improve your PR

**Comment by cyrildewit** [comment]
I tested my suggestion and it worked. Yes, just put that code between `public function down(){` and `}`.

```php
public function down()
{
    Schema::table('users', function (Blueprint $table) {
        $table->dropForeign(['role_id']);
    });

    Schema::table('users', function (Blueprint $table) {
        $table->integer('role_id')->change();
    });
}
```

**Comment by agoalofalife** [comment]
@cyrildewit no problem)
done

**Review by cyrildewit — APPROVED** [review]

**Comment by fletch3555** [comment]
We try to avoid changing migrations as existing users may not get the updated version.  Given this is only the `down` side of a migration that doesn't get published, I'm inclined to let it through.  Please just be cognizant of that for future changes to migrations.

**Review by fletch3555 — APPROVED** [review]

**Comment by shaunthegeek** [comment]
fixed, but has not release?

suggest: should not close issue, until release. create a label "to be release" for it.

**Comment by emptynick** [comment]
Thats how Github works.
If a PR fixes an issue, it will auto-close that issue if the PR is merged into the default branch.

**Pull request merged**
