### PR TITLE
Add classname to view button in browse template

### PR DESCRIPTION
**Pull request by bbrala**
Add a classname to the view button in the browse template to be consistent with the other buttons. This is expecially handy when trying to select the buttons with javascript.

I was selecting a button with javascript because i didn't want to override the whole template, unfortunately selecting the view button is a bit tricky. This makes this a lot easier. Additionally, this makes the classnames consistent with the other buttons.

### CODE REVIEW

**Comment by emptynick** [comment]
Makes sense to me.
Only thing is that you created your branch from `1.0` and want to merge into `1.x-dev`, thats why its conflicting.
Because we are working on version `1.1` you might want to make your changes in [this line](https://github.com/the-control-group/voyager/blob/1.x-dev/src/Actions/ViewAction.php#L25)

**Comment by bbrala** [comment]
Oops, got confused, quite a few remotes on my repository since i working with @vblinden, will send in a new PR.

**Comment by emptynick** [comment]
You can just push a commit to your fork/branch, it will automatically update here as well.

**Comment by bbrala** [comment]
Since the change is so small, i'll remake to make sure rebasing doesn't cause problems.

**Pull request closed without merging**
