### PR TITLE
Replace 'or' with isset check in blade templates

### LINKED ISSUE #3561: Unable to create or edit Menus and Categories
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.1.20
 - Database: [MySQL] [5.7.19]

## Description

I just made a fresh installation of the Laravel Framework and installed the Voyager package, the installation was successful. But when ever i try to create or edit pages, categories via the admin panel i get the error in the image below

## Steps To Reproduce
1. Go to the voyager admin panel 
2. Click on 'Pages' in the side navigation menu
3. Click 'Add new' page or 'Edit' an a existing page

## Expected behavior
An ErrorException is rendered 

## Screenshots
voyager error

## Additional context
The same error also happens when you navigate to Categories in the side navigation menu and do the same actions.

### PR DESCRIPTION
**Pull request by shenxn**
In [PR#23532](https://github.com/laravel/framework/pull/23532/files). Laravel removed the Blade operator 'or' for version 5.7. It is also in the [Upgrade Guide](https://laravel.com/docs/5.7/upgrade).  This change causes 'Undefined property' error in several pages.
I changed the 'or' operators with isset checks.

Fixes #3561

### CODE REVIEW

**Comment by emptynick** [comment]
There's one more here:
https://github.com/the-control-group/voyager/blob/e41cb82fd8c9abc944039450c12e905a2f82765e/resources/views/menu/bootstrap.blade.php#L58

I will have a look if there are more.

**Comment by cotiga** [comment]
As it is backward compatible, I delete my pull request #3553
Thank's

**Review by fletch3555 — APPROVED** [review]

**Review by fletch3555 — CHANGES_REQUESTED** [review]
Please update the menus/bootstrap view mentioned by @emptynick. Then we can get this merged in

**Review by fletch3555 — APPROVED** [review]

**Comment by shenxn** [comment]
> There's one more here:
> [voyager/resources/views/menu/bootstrap.blade.php](https://github.com/the-control-group/voyager/blob/e41cb82fd8c9abc944039450c12e905a2f82765e/resources/views/menu/bootstrap.blade.php#L58)
> 
> Line 58 in [e41cb82](/the-control-group/voyager/commit/e41cb82fd8c9abc944039450c12e905a2f82765e)
> 
>  <a href="{{ url($item->link()) }}" target="{{ $item->target }}" style="{{ $styles }}" {!! $linkAttributes or '' !!}> 
> I will have a look if there are more.

@fletch3555 I've updated the view.

**Pull request merged**
