### PR TITLE
Minor spelling mistake

### PR DESCRIPTION
**Pull request by belthaZornv**
Fixed spelling mistake realationship to relationship.

### CODE REVIEW

**Comment by fletch3555** [comment]
@belthaZornv, can you please update your branch? Pull `1.0` into your `patch-1` branch then push. 
 Alternatively, you can enable public write access to your fork, and we can do it for you.  This is needed for us to merge the PR

**Comment by belthaZornv** [comment]
@fletch3555 sure will do; may I ask where you keep track of changes? I can't seem to find a CHANGELOG.md or something similar.

Also I believe it's based on 1.0, and there are no changes on 1.0 since then.

**Comment by fletch3555** [comment]
We keep track of changes in the release notes for each release on github.  This is a fairly recent practice, so you won't see it on all releases.

Also, the comparison github is making is between your branch and the branch it's going into, not the branch it was started from.

Thanks

**Comment by belthaZornv** [comment]
@fletch3555 I've added you as a collaborator to be able to edit the branch, I don't quite understand what you're after, I apologise. - I pulled your official 1.0 into the patch-1 branch and pushed into patch-1 branch. Is there any documentation regarding how you do PRs that I might follow?

**Review by fletch3555 — APPROVED** [review]

**Comment by fletch3555** [comment]
👍

**Pull request merged**
