### PR TITLE
Support single/multi file removal

### LINKED ISSUE #1160: Image - Input Type => have no option to delete the image.
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 5.6
- Database Driver & Version: MySQL

### Description:
Haw can we delete the image from an image input type ?

### LINKED ISSUE #2178: Unable to empty/delete/reset image field
- Laravel Version: 5.5.19
- Voyager Version: 1.0.7
- PHP Version: 7.1.9

### Description:

Am unable to reset/delete/remove field when editing a resource (a post page).

This past issue shows that this might be a regression bug: https://github.com/the-control-group/voyager/issues/1160

### Steps To Reproduce:

As seen from the screenshot below, there is no delete icon/button/link over the picture or any other UI element. Also checked from HTML code to verify there is no corresponding elements without possible styling either:
image

### PR DESCRIPTION
**Pull request by edvincandon**
Fixes #2178  fixes #1160

Currently it's only possible to delete images for the multiple images field type.
I updated the VoyagerMediaController to handle both single and multiple file removal and tried to make it more generic.

Changes are reflected in the views as well + a little styling I can remove if it doesn't fit : the cross button was currently floating below the images, I set it to `position: absolute` for now.

Tested on:
- single files
- multiple files
- single images
- multiple images

### CODE REVIEW

**Comment by nicolaszanghi** [comment]
When do you plan to merge this pull request ?

**Comment by emptynick** [comment]
Once it's tested properly.

**Comment by edvincandon** [comment]
> Once it's tested properly.

Hey @emptynick could you clarify - do you need me to write some unit/functional tests ?

**Comment by fletch3555** [comment]
Added testing would be great if you have the time/motivation, but @emptynick was referring to one of the maintainers testing it locally to verify it works as intended and doesn't introduce any obvious bugs.

**Comment by emptynick** [comment]
I commited a more generic "File removed" and "File does not exist" translation, because it was always saying "Image removed" no matter the type of the file.
Otherwise its working well.

**Review by emptynick — APPROVED** [review]

**Review by fletch3555 — APPROVED** [review]

**Pull request merged**
