### PR TITLE
Fix drop down multilevel admin menu

### LINKED ISSUE #2125: Multilevel menu drop down bugs
- Laravel Version: 5.5.*
- Voyager Version: dev-master
- PHP Version: 7.1.8-1
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.26-MariaDB

### Description:
The drop down for sidebar menu only works for 2 levels menu. I tried to create 3 levels menu, but when I click the 2nd level drop down it close the 1st level dropdown. 

### Steps To Reproduce:
1. Go to Menu Builder
2. Click Builder button
3. Create New Menu Item (Menu 1)
4. Create New Menu Item (Menu 2)
5. Arrange them so that it become 3 level menu
e.g
Menu 1 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Menu 2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Dashboard
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Database
screenshot from 2017-10-31 03-03-06

### PR DESCRIPTION
**Pull request by ta-tikoma**
Fixes #2125

### CODE REVIEW

**Comment by emptynick** [comment]
This needs to go to the 1.x branch because it requires the user to republish the assets.

**Review by emptynick — APPROVED** [review]
That's working, thanks!

**Comment by therepairshack** [comment]
I'm using v1.1 and i'm still experiencing this issue. I can see that app.js has the changes that were merged into 1.1 but it's still doing the same thing. Am I missing something??

**Comment by lamualfa** [comment]
Still not working.

**Comment by fletch3555** [comment]
This is 4 years old and already merged. Please open a new issue with an appropriate description of your problems

**Comment by lamualfa** [comment]
> This is 4 years old and already merged. Please open a new issue with an appropriate description of your problems.

@fletch3555 @emptynick Ok, Done: https://github.com/the-control-group/voyager/issues/5713.

Also, all my PRs seem crucial and related to the other issues. Hopefully, you can review it:

- https://github.com/the-control-group/voyager/pull/5714
- https://github.com/the-control-group/voyager/pull/5712
- https://github.com/the-control-group/voyager/pull/5703

**Note:** it seems that the `publishable` folder will cause conflicts between my PRs.

**Comment by justgkp** [comment]
Multilevel dropdown menu issue not yet fixed. I think Voyger team is least bothered about it and are not giving a proper solution as well. Because of this I am not able to use Laravel.

**Comment by fletch3555** [comment]
> This is 4 years old and already merged. Please open a new issue with an appropriate description of your problems 

@justgkp ^

**Pull request merged**
