### PR TITLE
fix bread radio_btn formfield list undisplay bug

### PR DESCRIPTION
**Pull request by Feiir**
parse error occurs when the data of radio is list ,fix it

### CODE REVIEW

**Comment by MrCrayon** [comment]
Can you post an example on how you are defining radio options in BREAD details for the error to occur?

**Comment by Feiir** [comment]
BREAD details eg :{
    "default": 0,
    "options": [
        "open",
        "close"
    ]
} 
this triggers the problem

**Comment by emptynick** [comment]
It shouldn't be an array but an object, as written in the docs.

**Comment by Feiir** [comment]
ok i got it

**Pull request closed without merging**
