### PR TITLE
Fix validation rule for image on update

### PR DESCRIPTION
**Pull request by DrudgeRajen**
This PR will fix the Bread validation bug for image on edit mode.

### CODE REVIEW

**Comment by fletch3555** [comment]
Just to confirm, this is fixing #3686?  If so, please add `Fixes #3686` to your PR description.  That will automatically close the other issue when this gets merged

**Comment by DrudgeRajen** [comment]
@fletch3555 Nope. It will only fix the validation message showing on edit, even if the field has an image.

**Comment by harunthuo** [comment]
this is it. thankyou DrudgeRajen

**Comment by emptynick** [comment]
I think we should unset the validation-rule based on `$request->ajax()`, not if the field is just absent from the request.
Edit: that wouldn't work, sorry.

**Comment by DrudgeRajen** [comment]
> I think we should unset the validation-rule based on `$request->ajax()`, not if the field is just absent from the request.
> Edit: that wouldn't work, sorry.

@emptynick  sorry, I didn't get that.

**Comment by farismohammed** [comment]
Same Problem in Edit With Multiple Images..."please select one or more files"..

**Comment by minhdanh** [comment]
Any updates on this issue?

**Comment by MrCrayon** [comment]
Superseded by Action specific validation rules in #4562

**Pull request closed without merging**
