### PR TITLE
Optional json_encode in selectMultiple

### PR DESCRIPTION
**Pull request by mcmc4519**
if model has casts and cast is json or array, we are don't need json_encode in selectMultiple

### CODE REVIEW

**Comment by mcmc4519** [comment]
I can't understand, what I should to fix in the code for styleci?

**Comment by emptynick** [comment]
You dont need to fix StyleCI, it will be fixed automatically after merge.
But TravisCI **has** to pass.

**Comment by mcmc4519** [comment]
> You dont need to fix StyleCI, it will be fixed automatically after merge.
> But TravisCI **has** to pass.

I can't understand, why phpunit has error, can you help me? It's my first public PR

**Comment by mcmc4519** [comment]
> You dont need to fix StyleCI, it will be fixed automatically after merge.
> But TravisCI **has** to pass.
I'm sorry, I'm found error.

**Comment by mcmc4519** [comment]
@emptynick can you see my pullrequest? Travis has been done successfully.

**Comment by cotiga** [comment]
You must add newline at end of file

**Comment by mcmc4519** [comment]
> You must add newline at end of file

why? for what? I can't understand

**Comment by emptynick** [comment]
Just dont worry about StyleCI.

**Comment by mcmc4519** [comment]
What need for approve my pullrequest?

**Comment by emptynick** [comment]
Time. You changed the signature of a method which makes it a breaking change, so it can't be merged in a Patch-Version.

**Comment by fletch3555** [comment]
I don't really like passing `$data` around so much.  Closing this.

**Pull request closed without merging**
