### PR TITLE
Replace ?? operator with isset way

### LINKED ISSUE #3067: In DataType.php line 186:   syntax error, unexpected '?'
- Laravel Version: v5.4.30
- Voyager Version: 1.1
- PHP Version: 5.6.30
- Database Driver & Version: 5.5.58-cll - MySQL Community Server (GPL)

### Description:
On new install  appear  _DataType.php line 186:   syntax error, unexpected '?'_  
before     _php artisan voyager:install_

### Steps To Reproduce:

install laravel :
composer create-project laravel/laravel laravel
______
in project name:
composer require tcg/voyager
_____
add the Voyager Service Provider 
------
 Update the "config/database.php" for 'mysql'
'engine' => null,
with
'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',

-----
Update the "app/Providers/AppServiceProvider.php" with
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        // Specified key was too long error, Laravel News post:
        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

php artisan voyager:install 

and crash

### PR DESCRIPTION
**Pull request by cyrildewit**
Fixes #3067

### CODE REVIEW

**Comment by fletch3555** [comment]
You didn't replace, you only added a line.

**Comment by cyrildewit** [comment]
**facepalm**

**Comment by cyrildewit** [comment]
This will still not fix his issue, because then we have to release a new version. Right?

**Review by fletch3555 — APPROVED** [review]

**Comment by fletch3555** [comment]
We'll definitely have to release a new version, but I don't see that as a problem.

**Pull request merged**
