### PR TITLE
Fixes #3246

### LINKED ISSUE #3246: Fix front-end on the "Viewing Database" page
https://github.com/the-control-group/voyager/blob/2bf3bc072205187323bdb2552e2264862abd48a9/resources/views/tools/database/index.blade.php#L24

Should be `colspan="2"`, right?

The table header has 2 columns but the table body has 3 columns.

image

### PR DESCRIPTION
**Pull request by andreich1980**
The table header has 2 columns but the body has 3.

### CODE REVIEW

**Comment by emptynick** [comment]
Where is the class `no-sort` actually used?
Edit: Guess I was too fast

**Comment by andreich1980** [comment]
@emptynick It seems I screwed up by adding the commits to a wrong PR :/

**Comment by andreich1980** [comment]
@emptynick  `no-sort` is used on `td`'s with actions for `browse` BREAD pages.
I think it's wrong, it should be on the `th` and it seems that there's no `.no-sort` class anywhere in the styles

Should I create new commits to another PR (actually, here https://github.com/andreich1980/voyager/pull/1/commits)? Or there's a way to move the commits?

**Comment by andreich1980** [comment]
the 2 wrong commits should be (and the changes already are) there #3249

**Comment by fletch3555** [comment]
@andreich1980, you need to be working in branches, not committing directly to `1.1` on your fork.  This is why those commits are appearing in both PRs.  I'm going to close them both, and you can open new ones when you've committed the changes to their own branches

**Pull request closed without merging**
