### PR TITLE
update menu_items column

### PR DESCRIPTION
**Pull request by xembill**
Add "q" column for update menu name query

### CODE REVIEW

**Comment by fletch3555** [comment]
uhh.... what's the "q" column supposed to be for?

**Comment by xembill** [comment]
`column not found: 1054 Unknown column 'q' in 'field list' (SQL: update `menu_items` )`

**Comment by fletch3555** [comment]
I get the feeling you're doing something wrong.  Can you provide the full error and stacktrace?

**Comment by xembill** [comment]
vendor/laravel/framework/src/Illuminate/Database/Connection.php

```
catch (Exception $e) {
            throw new QueryException(
                $query, $this->prepareBindings($bindings), $e
            );
        }
```

```
Illuminate \ Database \ QueryException (42S22)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'q' in 'field list' (SQL: update `menu_items` set `title` = Sistem Ayarlarıs, `updated_at` = 2018-02-08 18:43:15, `q` = adminv/menus/1/item where `id` = 17)
```

**Comment by fletch3555** [comment]
I need the full error (which you provided), AND the full stacktrace.

Also, when you have blocks of code to format, please surround it with triple-backticks (```) before and after.

**Comment by xembill** [comment]
```
Illuminate \ Database \ QueryException (42S22)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'q' in 'field list' (SQL: update `menu_items` set `title` = B_news, `color` = #000000, `updated_at` = 2018-02-09 12:55:50, `parameters` = , `q` = adminv/menus/1/item where `id` = 15)
```

```
/home/admin/web/***/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php
     * @param  array     $bindings
     * @param  \Closure  $callback
     * @return mixed
     *
     * @throws \Illuminate\Database\QueryException
     */
    protected function runQueryCallback($query, $bindings, Closure $callback)
    {
        // To execute the statement, we'll simply call the callback, which will actually
        // run the SQL against the PDO connection. Then we can calculate the time it
        // took to execute and log the query SQL, bindings and time in our memory.
        try {
            $result = $callback($query, $bindings);
        }
 
        // If an exception occurs when attempting to run a query, we'll format the error
        // message to include the bindings with SQL, which will make this exception a
        // lot more helpful to the developer instead of just the database's errors.
        catch (Exception $e) {
            throw new QueryException(
                $query, $this->prepareBindings($bindings), $e
            );
        }
 
        return $result;
    }
 
    /**
     * Log a query in the connection's query log.
     *
     * @param  string  $query
     * @param  array   $bindings
     * @param  float|null  $time
     * @return void
     */
    public function logQuery($query, $bindings, $time = null)
    {
        $this->event(new QueryExecuted($query, $bindings, $time, $this));
 
        if ($this->loggingQueries) {
Arguments
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'q' in 'field list' (SQL: update `menu_items` set `title` = B_news, `color` = #000000, `updated_at` = 2018-02-09 12:55:50, `parameters` = , `q` = adminv/menus/1/item where `id` = 15) ◀"

```

**Comment by emptynick** [comment]
And you get this error when you do what?

**Comment by xembill** [comment]
when update menu name or menu's other description.

**Comment by fletch3555** [comment]
@xembill, do you get this with a fresh install?  I'm inclined to believe not since nobody else is complaining about it.  This means it's something to do with your app (forgot to publish/run migrations after upgrading or something like that).

In either case, we can't support you unless you give us what we ask for, specifically the FULL stacktrace

**Comment by xembill** [comment]
@fletch3555 yes thats fresh install and already publish migrations. 
More, I have already shared 2 message above stacktrace. 
Its just "Column not found: 1054 Unknown column 'q' in 'menu_items"

When I added 'q" column in menu_items table its works.

**Comment by fletch3555** [comment]
No, you've provided the error message.  The stacktrace will be multiple lines long and tell me the history of function calls that lead to that error being displayed.

**Comment by fletch3555** [comment]
Closing due to inactivity.  Once you provide the requested information, it can be reopened for review

**Comment by demiurge-ash** [comment]
This is due to specific nginx configuration:
```
location / { try_files $uri $uri/ /index.php?q=$uri&$args; }
```
this adds another parameter **q=admin/menus/1/item**

perhaps the Voyager should take only the necessary parameters, but not everything

**Pull request closed without merging**
