### PR TITLE
Show 'none' only on first page

### PR DESCRIPTION
**Pull request by howdu**

### CODE REVIEW

**Comment by fletch3555** [comment]
Why would there be multiple pages if you're showing none....?

**Comment by fletch3555** [comment]
The newest change seems unrelated to the first one. Is that correct?

**Comment by fletch3555** [comment]
Again latest change is unrelated.  I'm closing this for now.  We prefer each PR only have one set of related changes.  Each of these need to be in their own branch

**Comment by howdu** [comment]
Sorry I don't know how to do that. I'll create them as separate issues.

**Comment by MrCrayon** [comment]
@howdu is best practice to create a new branch for every feature or bug fix, you can do:
`git checkout -b fix-ordering-bread 1.3`

**Pull request closed without merging**
