### PR TITLE
Use a label tag element for the remember me text

### PR DESCRIPTION
**Pull request by apiaget**
Hello !

I suggest replacing the span by a label on the login screen of the admin panel.

With this change, clicking on the remember me label also clicks on the associated checkbox.

There is no visual change (tested on Firefox, Chrome and Edge).

Any feedback is welcome ;-)

### CODE REVIEW

**Comment by apiaget** [comment]
Oups I wanted to create a second pull request for this modification but my commit came in this one.

So I also changed the url links to the tinymce fonts from `voyager-assets/?path=...` to `voyager-assets?path=...`.

This modification removes mixed content errors and therefore the broken UI as we could see in the screenshots of that issue : #4137 

I couldn't find any non minified source for the skin.min.css file so I assumed that the modification had to be done there.

Any feedback is welcome ;-)

**Comment by fletch3555** [comment]
The slash before the querystring shouldn't cause any mixed-content errors.  Can you revert that change and open a separate issue describing what you're seeing and why you think this is the solution?

**Comment by apiaget** [comment]
I reverted the commit about the TinyMCE problem.

I should add that there is already an issue describing that exact problem, I will add more screenshots and informations to it : #4137 

I may submit a second pull request about that TinyMCE after that.

**Review by emptynick — APPROVED** [review]
Can't hurt. Thanks

**Review by fletch3555 — APPROVED** [review]

**Pull request merged**
