### PR TITLE
Fix SQL Issue with multiple orderBy('order')

### PR DESCRIPTION
**Pull request by tjventurini**
Fixing SQL Issue: A column has been specified more than once in the order by list. Columns in the order by list must be unique.

Just had this issue on a MsSQL server. Whenever the menu items should be shown, I was facing the error from above. And I figured out, that there is indeed the `orderBy('order')` applied multiple times: Once in `Menu::display()` and the other time in the relationship itself, on `MenuItem::children`. 

Since I think it makes somehow sense to sort the MenuItems per default, I decided to remove the `orderBy` in the `Menu::display` method. But this MR is just to share the awareness of the issue, so feel free to do something else to fix the issue 😉

Have a great day! 😁

### CODE REVIEW

**Comment by MrCrayon** [comment]
Is ordering working as expected with this PR?

I see that order was introduced first in #1811 and then it was introduced in `MenuItem::children` with #4186.

P.S.
It looks like it should work because `display` is also calling `children` but I didn't test it.

**Comment by tjventurini** [comment]
Looking good for me :smiley: 

Bildschirmfoto von 2020-06-19 09-11-32

The only difference is, that `orderBy('order')` is only applied once now.

**Comment by tjventurini** [comment]
Is this going to be merged or will it be fixed somewhere else?

**Comment by emptynick** [comment]
I think the order should be applied in `display()` not `children()`.

**Comment by tjventurini** [comment]
Either way, It's probably gonna take some time until it's merged so feel free to update it meanwhile.

**Comment by emptynick** [comment]
Where is that second ordering tho?
Is it this one?
https://github.com/the-control-group/voyager/blob/8d60fe15d5b51393edf07117d347de16e0f0f4cd/src/Models/Menu.php#L74


Edit: Nevermind. In the model.

**Comment by tjventurini** [comment]
awesome, thx 👍

**Review by emptynick — APPROVED** [review]

**Pull request merged**
