### PR TITLE
BugFix:Undefined variable: dataRow

### LINKED ISSUE #3646: Cannot Add BREAD - Undefined variable: dataRow
## Version information

 - Laravel: v5.7.9
 - Voyager: v1.1
 - PHP: 7.1
 - Database: 10.1.36-MariaDB 

## Description

After I create a table using the database manager tool, and then go into BREAD tool and click add BREAD to this table, i get the Whoops error "Undefined variable: dataRow". Upon further inspection, I noticed that there is no record in the data_types table created for the new table I created.

I have tried adding a new table with a model, and without a model.

## Expected behavior
The BREAD add/edit screen should appear.

### PR DESCRIPTION
**Pull request by DrudgeRajen**
fix #3646

### CODE REVIEW

**Review by fletch3555 — DISMISSED** [review]

**Comment by fletch3555** [comment]
Very quick work on this. Thank you!

**Comment by fletch3555** [comment]
@DrudgeRajen can you resubmit this PR with a new branch cut from 1.1 instead of 1.x? You should always start from the latest release stream, else we run the risk of prematurely introducing other changes.

**Comment by DrudgeRajen** [comment]
@fletch3555 Sorry, I was away and hadn't checked the notifications. This issue was roadblocker. What is your plan for new release with the fix ?

**Comment by fletch3555** [comment]
No worries.  Wasn't sure how long you were going to be, so I opened a new PR for it.  Waiting on someone else to approve it (we don't let anyone approve their own PRs), and they're all asleep, so it'll likely be a few more hours.  Once they approve and merge it, we'll release v1.1.9 with this fix (and one other very minor one)

**Comment by DrudgeRajen** [comment]
Hope to see new release soon  :+1:

**Pull request closed without merging**
