### PR TITLE
Disable translations

### PR DESCRIPTION
**Pull request by howdu**
If multilanguage is disabled in config don't translate menu

### CODE REVIEW

**Review by fletch3555 — APPROVED** [review]

**Comment by MrCrayon** [comment]
I know this has already been merged but I just saw it.

There is no explanation why this pull request is needed but I was thinking that if leaving getTranslatedAttribute can cause any problem it should be addressed in getTranslatedAttribute Method of Translatable Trait, otherwise we should check everywhere if multilingual is enabled.

Am I wrong?

**Comment by fletch3555** [comment]
That's a very good point @MrCrayon.  Would you like to open a PR with that change?  If you're busy, I can take care of it.

**Comment by MrCrayon** [comment]
@fletch3555 I can do it but I don't have clear what's the problem this pull request was trying to resolve. Is there a related issue that I can check?

**Comment by howdu** [comment]
If multi language is disabled from config don't run translation database queries. 

The call to getTranslatedAttribute() from Models/Menu.php needs to work similar to is_bread_translatable() checking if voyager.multilingual.enabled.

**Comment by MrCrayon** [comment]
So if I understand it correctly there is no issue solved but it's a performance improvement.

**Pull request merged**
