### PR TITLE
Verify if the thumb resize is a string of null

### PR DESCRIPTION
**Pull request by migueldevpt**
In the SingleImage ContentType it's verified if the thumb resize is a string of null but not on the MultipleImage Class.
This code places the same verification on the MultipleImage Class.

### CODE REVIEW

**Comment by emptynick** [comment]
Not really sure why one would use null as a string, but since we check the same for a single Image I guess this is fine?!

**Comment by migueldevpt** [comment]
I do agree that it makes sense to set it to null only when it is null not when it is a string of null.

But if the SingleImage Class is set to only accept null instead of a string of null the default dummy seeder for the posts needs to also be changed because it uses for the image.details a string of null in the resize height option.

This being how if found this diference in the Single and MultipleImage Classes

**Comment by emptynick** [comment]
You mean this?
https://github.com/the-control-group/voyager/blob/ada5e4abaf69588059fb01a874392c1bd4cabc7a/publishable/database/dummy_seeds/PostsTableSeeder.php#L140
Thats the height.

**Comment by migueldevpt** [comment]
That's exactly the line. 
https://github.com/the-control-group/voyager/blob/ada5e4abaf69588059fb01a874392c1bd4cabc7a/src/Http/Controllers/ContentTypes/Image.php#L73-L75
If the previous line would be changed to only accept null and not 'null' would it not be required to also change that seeder?

**Review by fletch3555 — APPROVED** [review]

**Pull request merged**
