### PR TITLE
Slugify for Russian charmap

### PR DESCRIPTION
**Pull request by taiwanleaftea**
Slugify for Voyager - Russian map #3027

### CODE REVIEW

**Comment by emptynick** [comment]
I think it's better to "fix" the way those characters are replaced.
This way we keep language-specific things inside the array.

**Comment by taiwanleaftea** [comment]
I agree, but the problem is, that 'ь' and 'ъ' should be just removed from the transliterated string: 
i.e. платье -> plate or олень -> olen
So the character map should have special token to remove letter from the sting.

**Comment by MrCrayon** [comment]
@taiwanleaftea Can't we just set `'ь':''` and other cases in __map_russian_?
https://github.com/the-control-group/voyager/blob/af482b70eda00b94b8e18bb2d7f60e6d6a3b0333/resources/assets/js/slugify.js#L205

Edit:
looks like it's already there :thinking:

**Comment by taiwanleaftea** [comment]
It's already set, but the "replace charmap cycle" doesn't replace this letters and leave them "as is". Later **regexp replace(/[^a-z0-9]/g, _sep)** replaces the letters for separator.

**Comment by MrCrayon** [comment]
Then I think we should fix that, most probably the problem is here:
https://github.com/the-control-group/voyager/blob/af482b70eda00b94b8e18bb2d7f60e6d6a3b0333/resources/assets/js/slugify.js#L97
That should pass if `this.chars[str.charAt(i)]` is empty so we need to change how it's checked.

**Comment by MrCrayon** [comment]
This should work:
```javascript
_slug += (this.chars.hasOwnProperty(str.charAt(i))) 
```

**Comment by taiwanleaftea** [comment]
Yes, it works. Will you make the changes or should I do PR?

**Pull request closed without merging**
