### PR TITLE
Fixed the problem when user role is NULL

### PR DESCRIPTION
**Pull request by alkhachatryan**
Fixed the unknown issue related with NULL user role

### CODE REVIEW

**Comment by emptynick** [comment]
Same as in #3962.
This is basically just calling `$this->load('role')` again, which might fail again because it failed doing the same before.

**Comment by fletch3555** [comment]
I don't really like this solution.  I'd rather see `->load('role')`, but as @emptynick said, it still may not solve the problem.

**Comment by alkhachatryan** [comment]
That's why I prefer this way to solve it.

**Comment by emptynick** [comment]
Overly dramatic visualization of whats happening and what you are doing:
```php
$value = null;
$value = 1; //aka $this->load('role'); < fails

if (!$value) {
    $value = 1; //aka $this->load('role'); < might fail again
}
```
Instead of just manually trying to assign the role (again) you/we should find out why its failing in first place.
Calling `Role::find( Auth::user()->role_id );` is effectively the same as `load('role')`.
It is failing the first time, and might fail the second time as well, and maybe even a third, fourth...time.

**Comment by alkhachatryan** [comment]
@emptynick it's not the same.

If I remove this "dramatic" code, the error appears. It's really not the same

**Comment by emptynick** [comment]
Take a look at the source.
`load(...)` does nothing else than `$this->x = Model::find(y)`.
It's more helpful to find the cause of the problem instead of "fixing" it by doing the same again - believe me.

**Comment by wishbone-productions** [comment]
Same here, after updating the admin user it deletes the user_roles and nulls the role_id. looks like the bug is reintroduced. Maybe it has something to do with upgrading to laravel 5.8. Bug started to appear right after that.

php: 7.1.2
laravel: 5.8
voyager: 1.2.1

**Comment by emptynick** [comment]
Did you upgrade from 1.1 and followed the upgrade guide?

**Comment by wishbone-productions** [comment]
Yes done all off the steps as described.

Think this is part of the solution: https://github.com/the-control-group/voyager/issues/2451#issuecomment-470569735
But its a bit to dirty.

I'm not seeing rights the rights fields like, Default Role / Additional roles. Although i'm logged in as admin.

**Comment by wishbone-productions** [comment]
line 63 in edit-add.blade.php is passing the user model instead of the roles model.

`@can('editRoles', $dataTypeContent)`

Should be: 

` @can('edit',  Voyager::model('Role'))`

**Comment by emptynick** [comment]
Please show us a screenshot of your user bread settings

**Comment by wishbone-productions** [comment]
https://github.com/the-control-group/voyager/issues/2451#issuecomment-470938098

Sineld solution above worked for me.

**Pull request closed without merging**
