### PR TITLE
Fixed duplicated route name

### PR DESCRIPTION
**Pull request by ahmetbedir**
When I try to cache routes in Laravel 7, I get an error and I get the error that the same name is already being used in the message. To fix this problem, I changed the route names to be unique.

### CODE REVIEW

**Comment by hirbod** [comment]
I can confirm this issue.

 LogicException 
```

  Unable to prepare route [admin/menus/{menu}/order] for serialization. Another route has already been assigned name [voyager.menus.order].

  at vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:210
    206|             $route->name($name = $this->generateRouteName());
    207| 
    208|             $this->add($route);
    209|         } elseif (! is_null($symfonyRoutes->get($name))) {
  > 210|             throw new LogicException("Unable to prepare route [{$route->uri}] for serialization. Another route has already been assigned name [{$name}].");
    211|         }
    212| 
    213|         $symfonyRoutes->add($route->getName(), $route->toSymfonyRoute());
    214| 

      +32 vendor frames 
  33  artisan:37
```

and 

```
 Unable to prepare route [admin/users/order] for serialization. Another route has already been assigned name [voyager.users.order].

  at vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:210
    206|             $route->name($name = $this->generateRouteName());
    207| 
    208|             $this->add($route);
    209|         } elseif (! is_null($symfonyRoutes->get($name))) {
  > 210|             throw new LogicException("Unable to prepare route [{$route->uri}] for serialization. Another route has already been assigned name [{$name}].");
    211|         }
    212| 
    213|         $symfonyRoutes->add($route->getName(), $route->toSymfonyRoute());
    214| 

      +32 vendor frames 
  33  artisan:37
```

**Comment by hirbod** [comment]
I can confirm that this PR fixed the issue

**Comment by MrCrayon** [comment]
Related https://github.com/laravel/framework/pull/31755

@emptynick can we merge this before releasing 1.4?

**Comment by emptynick** [comment]
If you tested and approved it, sure.

**Comment by MrCrayon** [comment]
No, I didn't test it that's why I didn't approve it.

I'll try to find the time tomorrow, just wanted to let you know in case you were planning to release today. :wink:

**Review by MrCrayon — CHANGES_REQUESTED** [review]
Can you remove the naming for those two routes and revert changes in templates?
Thanks

**Review by MrCrayon — APPROVED** [review]

**Comment by hirbod** [comment]
@MrCrayon @emptynick this PR  is broken for me. I don't get the duplicate error message but this when I try to order a menu via drag and drop

`
{message: "Trying to get property 'model_name' of non-object", exception: "ErrorException",…}
message: "Trying to get property 'model_name' of non-object"
exception: "ErrorException"
file: "/home/vagrant/code/vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php"
line: 801
trace: [{file: "/home/vagrant/code/vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php",…},…]
`

**Comment by MrCrayon** [comment]
@Hirbod thanks for testing, this is the reason
https://github.com/the-control-group/voyager/blob/643b02b23f7758bbc3c1385dd6c919ec573e201e/src/Http/Controllers/Controller.php#L38

I'll send a fix tomorrow, looks like we need route names but I think we can still avoid to change templates since generated url is the same.

**Pull request merged**
