### PR TITLE
Add Ajax relation support - from #3448

### LINKED ISSUE #3581: Autocomplete for big amount of data in relationship
## Version information
 - Laravel: v5.6
 - Voyager: v1.1.5
 - PHP: 7.2

## Description of problem
I have in one of my relationships a big amount of data to display, the dropdown is filled by more than 30000 options and it makes the navigator crash.

## Proposed solution
Is there any way I missed to use Autocomplete Ajax dropdown for relationships field ?

### PR DESCRIPTION
**Pull request by vince83110**
Using #3448 , I made new PR with more clean code and commit. I also corrected some behaviors in the controller.

I didn't make any test since it depends on custom models and custom relations, and it's only code added.

Fixes #3581 closes #3448

### CODE REVIEW

**Comment by tnylea** [comment]
Hey @vince83110 This seems really cool.

I'm seeing some weird functionality in the current User to Many roles relationship. I did a fresh install of your PR and when I go to edit a user, this is what I'm seeing in the Additional roles:

screen shot 2018-09-26 at 2 36 20 pm

With no option to select multiple roles. This is the what happens on the current version:

screen shot 2018-09-26 at 2 35 55 pm

Let me know if you can get that fixed 👍 Or if I'm missing something.

Thanks! This will be really cool to have available.

**Comment by vince83110** [comment]
@tnylea Have you compiled the assets ? I put the new class `select2-ajax` to the select. And it seems your assets are not up to date since nothing happen to this new class. It works from me (see the label "Searching..." at the top of the list (it comes from select2-ajax new functionality) : 

image

**Comment by tnylea** [comment]
Awesome! Checking now 👍

**Comment by tnylea** [comment]
@vince83110 Yep, just tried again and I'm getting the same thing. Here are the steps you can use to reproduce what I'm seeing.

### Install a fresh version of Voyager
```
laravel new voyager-ajax
cd voyager-ajax
composer require tcg/voyager
```

### Delete the tcg/voyager repo for your repo
```
cd vendor/tcg
rm -rf voyager
git clone https://github.com/vince83110/voyager.git
```

### Create a new DB and add credentials to my `.env`

### Run Voyager Install

```
php artisan voyager:install --with-dummy
```

Then, when I try and create a new user I'm not seeing the select2 dropdown.

Can you try those steps and let me know if you are seeing the same thing? If not, Let me know 👍

**Comment by vince83110** [comment]
@tnylea It seems you need to compile asset before installation. The `voyager:install` command only copy asset files from **publishable** directory to public **directory**. I am not sure if I have to provide compiled assets or not. But I added the new _app.js_ compiled file. It should works now.

**Comment by fletch3555** [comment]
Please don't commit the compiled assets.  We have a script that will do that automatically once the PR is merged.

**Review by emptynick — APPROVED** [review]
Working perfectly fine for me. Thanks!

**Comment by Emerica** [comment]
Suggest making the the belongsTo  edit select query in the relationship blade
```
 $query = $model::find($dataTypeContent->{$options->column})->get();
```

The belongsToMany should get something like this.
```
$relationshipOptions = app($options->model)->whereIn($options->key, $selected_values)->get();

```


Chrome takes ages to load pages with select2 and lots of values.
Now with the above relations, we only need the selected objects from the database, the rest can be dynamically loaded.

These changes take a page load from minutes is some cases, to seconds if that.
Firefox seems to cope with the situation much better.

**Pull request merged**
