### PR TITLE
Fix relation error with Permission and role

### PR DESCRIPTION
**Pull request by xtrees**
change relation from hasMany to  belongsToMany

### CODE REVIEW

**Comment by fletch3555** [comment]
I feel like this was done intentionally, but I can't conceive of any possible reason why...  Did you have a problem that this fixed?

**Comment by xtrees** [comment]
I want get roles related to one permission.  They connected through middle table permission-role ，hasMany does not work should be belongs to Many

**Comment by fletch3555** [comment]
I agree that it is in fact (currently) a many-to-many relationship, which requires the use of `->belongsToMany()`, but I was just wondering if you ran into an issue, or if you were just looking at the code and thought it looked wrong.

**Comment by xtrees** [comment]
For example .I want list all of my roles who has the ability to manage posts so i can group users in those roles together. No need to check one by one

**Comment by xtrees** [comment]
When I do this.  Call the roles() it shows error so I only create My permission model override the roles function

**Pull request closed without merging**
