### PR TITLE
Add homepage link in login.blade.php

### PR DESCRIPTION
**Pull request by cotiga**
My Christmas present, a link to homepage!
Yes, he sorely lacking me when I disconnect from Voyager.
I don't know about you, but for me it's very helpful.

### CODE REVIEW

**Comment by fletch3555** [comment]
I can barely tell what you changed since you also made all those whitespace changes.

Having said that, Voyager should not presume your site is available at `/`.  So I don't think this we'll be able to add this into Voyager.  I'd like to get @emptynick's opinion though.

**Comment by cotiga** [comment]
The addition of the link is from line 93 to 96
The rest is only small syntax corrections

**Comment by fletch3555** [comment]
I'm going to decline this per my previous comment.

Also, in the future, please refrain from committing those whitespace/formatting changes.  All they do is pollute the pull request.

**Comment by cotiga** [comment]
OK it's noted. Thank's

**Pull request closed without merging**
