### PR TITLE
Create 2021_08_17_120402_alter_translations_table.php

### PR DESCRIPTION
**Pull request by Ronan-Lenor**
To resolve the problem mentionned here :
https://github.com/the-control-group/voyager/issues/5427

### CODE REVIEW

**Comment by emptynick** [comment]
Not sure if I'm wrong, but the `translations` table references a lot of stuff, not only `data_rows`.
So when I have an item for any model with the same ID of a `data_row` and I delete that entry, a random `data_row` will be deleted.

**Comment by Ronan-Lenor** [comment]
this is a one way cascading. `data_row` deletation trigger the deletation inside `translations`
but if a translation is deleted (by example through a menu_item deletation) then it won't cascade in `data_rows`
i did a test, everything look fine.

Edit: but it probably need further investigation.

**Comment by Ronan-Lenor** [comment]
this part should be removed but i can't reedit the file
`DB::table('translations')->whereNotIn('foreign_key', DB::table('data_rows')->select('id'))->delete();`
this should be replace with something like this
```
        // to avoid the Illuminate\Database\QueryException :
        // Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails
        Schema::disableForeignKeyConstraints();

        Schema::table('translations', function (Blueprint $table)
        {
            $table->foreign('foreign_key')->references('id')->on('data_rows')->onDelete('cascade');
        });

        Schema::enableForeignKeyConstraints();
```

**Comment by Ronan-Lenor** [comment]
i think i have found a better solution, some i will close this one

**Comment by Ronan-Lenor** [comment]
see here now :
https://github.com/Ronan-Lenor/voyager/commit/e6d6c80cb9b660973aa1ac8f667de407d1127620#commitcomment-55720069

**Pull request closed without merging**
