### PR TITLE
Fix to delete last BelongsToMany relation

### PR DESCRIPTION
**Pull request by vvvkor**
Fixes issue: https://github.com/the-control-group/voyager/issues/2476

There was alternative fix (adds hidden dummy input to view): https://github.com/the-control-group/voyager/pull/3112

But the issue should be fixed in controller - which is offered here.

### CODE REVIEW

**Review by tommykaira — CHANGES_REQUESTED** [review]
Fixes applied on the view and controller addressed the issue when deleting the last many-to-many value of a record.

**Comment by vvvkor** [comment]
@tommykaira Your review is a "Request changes", but I don't see what changes do you suggest. Am I missing something?

**Comment by marijnz0r** [comment]
Looks like a good solution, thanks for following up on my pull request.

**Comment by emptynick** [comment]
We have to merge one of the new profile PRs before we can merge this one, otherwise those issues will come back: https://github.com/the-control-group/voyager/issues/3010 or https://github.com/the-control-group/voyager/issues/2451
Just so you know why it takes a bit.

**Comment by emptynick** [comment]
Fixed in #3016.
Merged into 1.x

**Pull request closed without merging**
