### PR TITLE
Add in support for Laravel 7

### PR DESCRIPTION
**Pull request by midnite81**
This adds in support for Laravel 7

### CODE REVIEW

**Comment by emptynick** [comment]
Hey, thanks!
I just added testing against Laravel 7 so we can make sure everything works with it.

**Comment by midnite81** [comment]
Looks as though I missed the orchestra/tb dependency -  good spot :)

**Comment by emptynick** [comment]
Yeah it's always a bit painful to find the corresponding versions for all those packages.
Pushing some more things.

**Comment by midnite81** [comment]
This is why I love tests - makes finding bugs way more easy :)

**Comment by midnite81** [comment]
It looks like larapack/hooks only require composer/composer ~1.4 but the symphony/console isn't supported until ~1.10 (but it's in RC for now)

**Comment by emptynick** [comment]
Good catch.
`composer/composer` 1.9.3 (latest stable) supports `symfony/console` > 2.7 so I will updat the dependency in `larapack/hooks`.

**Comment by emptynick** [comment]
Turns out we have to wait for `composer/composer` to release something with support for `symfony/console` 5.0 for now.
Nothing we can do at the moment.

**Comment by midnite81** [comment]
Doh! That's annoying isn't it.

**Comment by emptynick** [comment]
Lucky us: https://github.com/composer/composer/releases/tag/1.10.0

**Comment by midnite81** [comment]
That's pretty good timing :)

**Comment by emptynick** [comment]
Now it looks like we have to drop support for PHP 7.2.

Edit: We have to have `laravel/ui` which requires at least Laravel 5.8 but we still support 5.5 (as it is LTS)

**Review by fletch3555 — APPROVED** [review]

**Review by emptynick — APPROVED** [review]

**Comment by midnite81** [comment]
Thanks @emptynick & @fletch3555 :)

**Pull request merged**
