### PR TITLE
Load relationship

### LINKED ISSUE #2870: Relationship not loaded in browse in some conditions
- Laravel Version: 5.5.39
- Voyager Version: 1.0.16
- PHP Version: 7.1.14
- Database Driver & Version: 10.1.30-MariaDB

### Description:
When using built in relationships defined in BREAD details field _label_ chosen doesn't show in browse 
if _timestamps_ are defined and no sorting is used.
The problem is a missing _->with($relationships)_ in VoyagerBreadController:

```
            if ($orderBy && in_array($orderBy, $dataType->fields())) {
                $querySortOrder = (!empty($sortOrder)) ? $sortOrder : 'DESC';
                $dataTypeContent = call_user_func([
                    $query->with($relationships)->orderBy($orderBy, $querySortOrder),
                    $getter,
                ]);
            } elseif ($model->timestamps) {
                $dataTypeContent = call_user_func([$query->latest($model::CREATED_AT), $getter]);
            } else {
                $dataTypeContent = call_user_func([$query->with($relationships)->orderBy($model->getKeyName(), 'DESC'), $getter]);
            }
```
I think it got lost with pull request  #937 , @victorlap noticed it but it looks like nobody replied so I don't know if there is a reason behind it even if I can't think of any.

### Steps To Reproduce:
Install Voyager with dummy
Edit posts bread adding to category_id:
```
{
    "relationship": {
        "key": "id",
        "label": "name",
        "method": "category"
    }
}
```
Browse Posts, only _category_id_ is shown instead of _name_

### PR DESCRIPTION
**Pull request by MrCrayon**
This fixes #2870

### CODE REVIEW

**Review by fletch3555 — CHANGES_REQUESTED** [review]
Instead of adding the relationships there, can you remove it from the other two and add it to the end of `$model::select('*')` on line 52, after moving that line down below the definition of `$relationships`?

**Comment by MrCrayon** [comment]
Thanks for suggestion, that looks much better.
I'm still quite new to Laravel Framework and Voyager so I try to change as less as possible.
I moved relationship up, if that's ok for you.

**Comment by defaultpage** [comment]
@MrCrayon, @fletch3555, works for me. Thanks.

**Comment by marktopper** [comment]
We're no longer accepting changes for the 1.0 branch since we're so close to a 1.1 release. Can you please update the PR to resolve the conflicts?

**Comment by MrCrayon** [comment]
I'm quite new on github, I checked the **Resolve conflicts** but in 1.x-dev changes should be applied to a different file _VoyagerBaseController_ so I'm not sure how I can resolve that.
Maybe it would be easier to submit a new pull request on 1.x-dev.
Suggestions?

**Comment by marktopper** [comment]
If you could do that, then it would be great.
Else we will leave this here, and hopefully I will get time to look into it :)

**Comment by MrCrayon** [comment]
Sure I'll check it later, thanks :)

**Comment by fletch3555** [comment]
Closing in favor of #2983

**Comment by morettyCat** [comment]
Hi there, I think something is going wrong in this section of code. Let me explain:

When you go to "Browse" some model and then you click on row's name on header's table, results are not being listed correctly.

### Steps to reproduce

1. Create a _First Model_ (paged server side) with timestamps
2. Create a _Second Model_
3. Create a _Pivot Table_
4. Create a relationship BelongsToMany in _First Model_ pointing to the _Second Model_ (using pivot table). 
5. Go to browse _First Model_
6. Click on the field that shows relationship in order to sortBy this field
7. Look how it comes **unordered** :(


### My suspicions

As far as I played in order to solve this, I was able to find something interesting:

When the request came with this :

/admin/firstmodel?page=1&sort_order=desc&**order_by=firstmodel_belongstomany_secondmodel_relationship**

then the VoyagerBaseController.php on the if condition on line 65:

65. `if ($orderBy && in_array($orderBy, $dataType->fields())) {`

gets resolved on the timestamp "else" on line 71:

71. `}elseif ($model->timestamps) {`

and that's not correct, because "**what if we have timestamps but we asked the UI to sort results by relationship?**" the logic in this file says that it will be sorted by timestamps, but that's not correct as we specifically selected a field to sort by.

### Temporary solution

Delete the eleseif statement placed above in order to go to the last "ELSE" which applies the order correctly.

I expect it's clear... it's my first post. Congratulations for that AMAZING project.

Any real solution? I supose that deleteing the elseif that deserves to a logical condition is not a real solution...

**Comment by defaultpage** [comment]
@morettyCat Hi! If I understand you correctly, then your problem is identical to [this one (#2661)](https://github.com/the-control-group/voyager/issues/2661).

**Comment by morettyCat** [comment]
Yes @ArtemMolotov ! I did not read this issue before, sorry for that, i'll try to solve this issue by this method (but as far as I can see, i'm on 1.1 and your link relates to 1.0 if I'm not wrong). But i'll read it before asking again, so sorry!

**Pull request closed without merging**
