### PR TITLE
Fix S3 disk found string length of 0

### PR DESCRIPTION
**Pull request by pamekar**
When using S3 as the default filesystem driver, you'll get this error when accessing the dashboard.

Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0 (View: /public_html/main/vendor/tcg/voyager/resources/views/media/manager.blade.php)

The error can be found in `/voyager/resources/views/media/manager.blade.php` on line 9.
```
 <div class="img_icon" :style="imgIcon('{{ Storage::disk(config('voyager.storage.disk'))->url('') }}'+file)"></div>
```
Adding a "/" to the `url` method solves this error. I opened an issue #4169 on this.

### CODE REVIEW

**Review by emptynick — APPROVED** [review]

**Comment by samuelwei** [comment]
Hi @emptynick this same issue is back with laravel 9, due to the filesystem changes, see: #5684 and https://github.com/laravel/framework/issues/41509 
Could you please fix this? My local workaround was to use "./" instead of "/", but not sure if this is a future proof and working with all filesystem drivers

**Comment by didix16** [comment]
Hello, I'm having the same issue. I'm using Laravel 9 and Voyager v1.6. Any fix for this problem?
imagen

**Comment by ash2osh** [comment]
{project folder}/vendor/tcg/voyager/resources/views/media/manager.blade.php

use ./ instead of /

in

               <div class="img_icon"
                                    :style="imgIcon('{{ Storage::disk(config('voyager.storage.disk'))->url('./') }}' + file)">

**Comment by George-nacouzi** [comment]
changing the vendor files is not a good practice, any better way to solve this ?

**Pull request merged**
