### PR TITLE
fix broken translation in menu builder

### LINKED ISSUE #2731: Multilanguage does not work on menus
- Laravel Version: 5.6.5
- Voyager Version: 1.x.dev
- PHP Version: 7.2 + argon2
- Database Driver & Version: mysql 5.7

### Description:
I can't get Voyager menus change the language. My site is running en and ru locales. I've enables multilanguage support in voyager.php file(see below). When I create a new menu item there is an option to set name for both locales(RU, EN). But when I change site language with App::setLocale() function, it does NOTHING. There are translations in the database. But Voyager isn't getting the current language and translating my menu. Why does it happen?

### Steps To Reproduce:
Fresh Voyager installation. Change configs to this:
app.php
```
'locale' => 'ru',
'fallback_locale' => 'en',
```
voyager.php
```
'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'ru',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'ru',
            'en',
        ],
    ],
```

### PR DESCRIPTION
**Pull request by yangqi**
Discovered this bug and spent some time fixing it. 

To reproduce, enable multilingual, and in menu builder, all the menu names do not display, only the links. They also don't fill the input boxes when editing.

The fix is as simple as removing htmlspecialchars(), which I think is unnecessary here, as the data is from the database not user inputs.

Fixes #2731

### CODE REVIEW

**Review by cyrildewit — APPROVED** [review]
Yupp, this did the job!

Quoting Laravel documentation:

> Blade {{ }} statements are automatically sent through PHP's htmlspecialchars function to prevent XSS attacks.

**Comment by cyrildewit** [comment]
Also, I think that you missed line 18: `data-parameters="{{ htmlspecialchars(json_encode($item->parameters)) }}`

**Comment by yangqi** [comment]
Thanks for the quoting, I have updated the request to remove that extra htmlspecialchars().

**Review by cyrildewit — APPROVED** [review]

**Review by fletch3555 — APPROVED** [review]

**Comment by fletch3555** [comment]
No idea how that got in there in the first place... good catch, thanks!

**Pull request merged**
