### PR TITLE
Bugfix/relationship field details

### PR DESCRIPTION
**Pull request by tjmckenzie**
Allows field details to be passed to a relationship field if supplied. Allows all display options to be accessed from the relationship field, to be used in CRUD forms.
Referenced from #2182

### CODE REVIEW

**Comment by tjmckenzie** [comment]
Any comments or review for this?

**Review by putchi — APPROVED** [review]

**Comment by sh4rifi** [comment]
this is not work.
Did you think about many to many relationship?

**Comment by d3turnes** [comment]
> this is not work.
> Did you think about many to many relationship?

File: Models\DataType.php

public function getRelationships($requestData, &$fields) {

     // $requestData['field_details_'.$relationship] = json_encode($relationshipDetails);
    
     $details = json_decode($requestData['field_details_'.$relationship], true);
     $merge = array_merge($details, $relationshipDetails);
     $merge['details'] = $details;
					
     $requestData['field_details_'.$relationship] = json_encode($merge);
}

Image1

File: resources/views/tools/bread/relationship-partial.blade.php

Add an textarea ( line 94 )


		<div class="relationship_details_content margin_top">
            <div class="col-xs-12" style="margin: 0px !important; padding: 0px !important;">
				<div class="alert alert-danger validation-error">
					{{ __('voyager::json.invalid') }}
				</div>
				<label>{{ __('voyager::database.relationship.relationship_details') }}</label>
				<textarea id="json-input-{{ ($relationship['field']) }}" class="resizable-editor" data-editor="json" name="field_details_{{ $relationship['field'] }}">
					@if(isset($relationshipDetails->details))
						{{ json_encode($relationshipDetails->details) }}
					@else
						{}
					@endif
				</textarea>
			</div>
		</div>

Image2

Result

Relationship [Belongs To Many]
Image2

Relationship [Belongs To]
Image2

bye

**Comment by emptynick** [comment]
Based on the comments this doesn't work. Also it doesn't implement a textbox to allow to actually set those additional details.
As this PR is untouched for nearly a year I'm going to close this.
Of course it can be reopened.

**Pull request closed without merging**
