### PR TITLE
Replace OR with ?? for Laravel 5.7 compatibility 

### PR DESCRIPTION
**Pull request by cotiga**
There are certainly more...

### CODE REVIEW

**Comment by fletch3555** [comment]
What version of php was that operator added in? 7.0? 7.1? We still technically support 5.6, so you'll definitely find a few older language constructs in use

**Comment by cotiga** [comment]
Ouch, I think you must think to no longer support the older version of Laravel (and therefore PHP)

Since PHP 7.0
http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

https://laravel.com/docs/5.7/upgrade
Blade
The or Operator

**Comment by emptynick** [comment]
L5.7 is just a few days old. we can't drop support for all other versions.
Instead we should manually test those variables with `isset` or something.

**Comment by cotiga** [comment]
Use #3562 (backward compatible)

**Pull request closed without merging**
