### PR TITLE
Better Coordinates formfield

### PR DESCRIPTION
**Pull request by mattrabe**
- Move into Vue
- Reveal lat+lng inputs, sync between map marker drag and lat+lng input changes
- Add Places Autocomplete, sync to map & lat+lng inputs

Screen Shot 2019-10-15 at 7 35 43 AM

### CODE REVIEW

**Comment by emptynick** [comment]
I think this might supersede https://github.com/the-control-group/voyager/pull/2963

**Comment by emptynick** [comment]
Are you done here?
Maybe we can get this in to 1.3

**Comment by mattrabe** [comment]
I intend to add some features to this today/tomorrow. Is there a timeline for 1.3 launch?

As a side-note, pull request #4460 should really be considered for the next release if it is not already, as it is a bug-fix.

**Comment by mattrabe** [comment]
I just pushed the planned feature additions. onChange callback, and options to turn off the Autocomplete and Lat, Lng inputs.

**Comment by emptynick** [comment]
I just pushed two commits.
One which brings your documentation to the index (so it can be found)
And one to translate all strings.

(I will let Travis run once I have some other things merged in)

**Review by emptynick — APPROVED** [review]

**Pull request merged**
