### PR TITLE
Fix Select2 search on additional attribute

### LINKED ISSUE #4561: I can't filter results on Select2
## Version information
 - Laravel: v6.5.0
 - Voyager: v1.3.0
 - PHP: 7.3.11
 - Database: MYSQL 15.1 10.4.8 MariaDB

## Description
When trying to filter a select2 results I'm getting "the results could not be loaded". I have a custom attribute in my relationship which is a result of 2 collumns of my model. eg. "id - description".

If I remove my custom attribute on Bread relationship the select2 filter works just fine.

## Steps To Reproduce
1. Create a custom attribute on the model
eg. 
    public $additional_attributes = ['full_grupo_conta'];

    public function getFullGrupoContaAttribute()
    {
         return "{$this->grupo_razao} - {$this->descricao_grupo}";
    }

2. Create a relationship
3. Select the custom attribute on the relationship and save
4. Add new register on BREAD
5. Try to filter select2 results

Capturar

Capturar2

Capturar3

Thanks!

### PR DESCRIPTION
**Pull request by MrCrayon**
Use collection filter when an additional attribute is used as label.

Fixes #4561

### CODE REVIEW

**Comment by livrosroberto** [comment]
Hello @MrCrayon 
thanks for the PR.
I tested your code and now the oposite situation is not returning any results after trying  to filter select2.

Let me explain better.

After implement your code a select2 combo with a custom attribute is ok, but a select2 combo with a regular model collumn (single collumn) isn't returning results.

Thanks man.

**Comment by MrCrayon** [comment]
@livrosroberto you are right, fixed. Thanks

**Review by emptynick — APPROVED** [review]

**Review by fletch3555 — APPROVED** [review]
Looks good

**Comment by DaLooK** [comment]
Thanks @MrCrayon & @fletch3555

**Pull request merged**
