### PR TITLE
Update French translations

### PR DESCRIPTION
**Pull request by AdrienPoupa**
Everything should be translated now :)

### CODE REVIEW

**Comment by emptynick** [comment]
@cotiga can you take a look if everything is fine here?

**Comment by AdrienPoupa** [comment]
Feel free to check the changes with Google translate or WordReference, I fixed many typos

**Comment by cotiga** [comment]
Super,
Quelques corrections tout de même si tu veux bien.

Mettre un **espace avant les points d'interrogation** (règle de typo française)

Je préférerais la formulation
> **l\'espace  d\'administration**

que

> **le panneau d\'administration**

Autres corrections utiles à mon avis :

`'dashboard'    => 'Tableau de bord',`

`'successfully_deleted'   => 'Supprimé avec succès',`

`'drag_drop_info'         => 'Glissez/déposez les éléments ci-dessous pour les réarranger.',`

`'symlink_missing_button' => 'Le réparer ?',`

Merci

**Comment by cotiga** [comment]
My apologies for my previous comments in French, Adrien will understand.
Some small corrections and we are close to perfection.
Thanks Adrien

**Comment by AdrienPoupa** [comment]
Hi @cotiga, good call for the interrogation marks. I applied your changes, except for the "admin panel" translation.

I think it would make sense to keep it as the "official" translation for the Windows Control Panel is Panneau de configuration: http://www.wordreference.com/enfr/control%20panel https://fr.wikipedia.org/wiki/Panneau_de_configuration_(Windows)

**Comment by cotiga** [comment]
> @cotiga can you take a look if everything is fine here?

Yes, thanks

**Review by emptynick — APPROVED** [review]

**Pull request merged**
