### PR TITLE
Don't show a widget if it's not accessible for the current user #2

### LINKED ISSUE #2248: Override widgets upon user's role
- Laravel Version: 5.5.21
- Voyager Version: 1.0.7
- PHP Version: 7.1.10
- Database Driver & Version:

### Description:

How (and where) can I set that?
\Config::set('voyager.dashboard.widgets', getWidgets() );

### LINKED ISSUE #2275: Dashboard shows things that shouldn't be available to Role
- Laravel Version: 5.5.21
- Voyager Version: 1.0
- PHP Version: 7.1.10
- Database Driver & Version: MySQL 14.14

I have a role that only should allow access to Posts. But I have to also allow the role to be able to "Browse Admin". So when that user logs in to the dashboard they see this:

screen shot 2017-11-22 at 2 54 10 pm

They shouldn't see the Users or Pages section at all. It doesn't seem like the dashboard is respecting the role privileges. If either of those is clicked, they get this:

screen shot 2017-11-22 at 2 54 01 pm

### PR DESCRIPTION
**Pull request by cyrildewit**
### Summary

All users can see the dashboard widgets currently, even when they don't have the permission to browse the widgets content.

At the moment, all dashboard widgets are registered inside the `VoyagerDummyServiceProvider`, but because the user object will always stay null, we can't check for access.

What I did, is adding a method called `shouldBeDisplayed` to the widget classes. Developers can do all kind of checks over here. For our need we can add a check for the `browse` permission. Then I added the `dimmers` method to the `Voyager` class. This will loop over the configured dashboard widgets and calls this method before registering it. A widget will be skipped if the method doesn't exists.

My first attempt: #3022

---

Fixes #2275
Fixes #2248

### CODE REVIEW

**Review by fletch3555 — CHANGES_REQUESTED** [review]
You're going to have to fix the tests to make TravisCI happy.  The current failures are because the test user doesn't have permissions, since they weren't needed for the dashboard page.  You'll have to update the tests to assign the appropriate permissions so the test user can see all 3 widgets.  Also, I'd appreciate it if you added a new test that verifies you CAN'T see it when you don't have permissions.

**Comment by cyrildewit** [comment]
I have changed the tests again.

It's currently as follows: I've created a unit test that will test the `dimmers` method on specific behaviour. For example: if `shouldBeDisplayed` returns false, it should not be inside the returned collection.

I also created a feature test that will make sure these widgets are being displayed on the dashboard page. It will also test each widget on access. A user without the `browse_pages` permissions, shouldn't see the `PageDimmer` widget.

I also removed the test that will verify if the `display()` method renders the widgets, because `arrilot/laravel-widgets` is already testing it over [here](https://github.com/arrilot/laravel-widgets/blob/master/tests/WidgetGroupTest.php#L21). Beside that, we should be able to change the blade partial without having to update the`rendered_widgets.html` file in my opinion.

**Comment by cyrildewit** [comment]
@fletch3555 what's your opinion about this: currently if the method `shouldBeDisplayed` doesn't exists, the widget will not be registerd.

Or do you prefer registering the widget anyway?

**Comment by fletch3555** [comment]
Can we have a "BaseDimmer" that contains a "return true" default for that method? Then all dimmers will have it.  We'll just have to add that to the docs.

**Review by fletch3555 — DISMISSED** [review]

**Review by fletch3555 — APPROVED** [review]

**Comment by fletch3555** [comment]
Bumping to `1.x` for a future v1.2 release since the new BaseDimmer and function call would break custom dimmers that may exist.

**Pull request merged**
