### PR TITLE
WIP: Update for Laravel 5.6 support

### PR DESCRIPTION
**Pull request by riotCode**
TODO:

- [ ] Identify new supporting package versions
- [ ] Identify Laravel 5.6 breaking changes for Voyager (if any)
- [ ] ....more to come...

### CODE REVIEW

**Comment by fletch3555** [comment]
We will not be supporting Laravel 5.6 in the `v1.0` stream.  Instead, we've already added support in the `1.x-dev` branch (as of this morning), so v1.1 will support it when we release it.

Thank you for the effort though!

**Comment by riotCode** [comment]
@fletch3555 Ah, ok that makes perfect sense. Any info on when to expect 1.1 or is it TBD?

Also, sorry not trying to be pushy, I know 5.6 was just released. Just would like to know what to expect is all :)

**Comment by fletch3555** [comment]
TBD.  We still have quite a bit of docs and tests to do.  If you'd like to help, you can check out the 1.x-dev branch and run through it. We need to figure out where the docs differ so we know what still needs to be filled out.

**Comment by riotCode** [comment]
@fletch3555 cool, thanks. I'll have a look and see if I can help with anything 👍

**Pull request closed without merging**
