### PR TITLE
Enable customization of TinyMCE init options

### LINKED ISSUE #4551: Tinymce modify settings before initilized
## Version information
- Laravel: v6.4.0
- Voyager: v1.3.0
- PHP: 7.2
- Database: Mysql 10.4.5-MariaDB

## Description of problem
Tinymce is missing the paste plugin to clean this up automatically. For some reasons the HTML below completely breaks Laravel if it's echoed in blade. We have admin users who copy text from Word into the html editor.  

## Proposed solution
Understand that not everybody needs the paste plugin so we need a way of modifying tinymce options before it's initilized. The tinymce_setup_callback function is unable to add plugins after tinymce has been loaded. 

I've [seen examples](https://github.com/the-control-group/voyager/issues/1945#issuecomment-415986744) where you can completely remove the editor and re-initialise it but this is not ideal because tinymce is already slow enough loading once. 

## Additional context
```html
<p><!-- [if gte mso 9]><xml>
 <w:LatentStyles DefLockedState="false" DefUnhideWhenUsed="true"
  DefSemiHidden="true" DefQFormat="false" DefPriority="99"
  LatentStyleCount="276">
  <w:LsdException Locked="false" Priority="72" SemiHidden="false"
   UnhideWhenUsed="false" Name="Colorful List Accent 5"/>
  <w:LsdException Locked="false" Priority="73" SemiHidden="false"
   UnhideWhenUsed="false" Name="Colorful Grid Accent 5"/>
  <w:LsdException Locked="false" Priority="60" SemiHidden="false"
   UnhideWhenUsed="false" Name="Light Shading Accent 6"/>
  <w:LsdException Locked="false" Priority="61" SemiHidden="false"
   UnhideWhenUsed="false" Name="Light List Accent 6"/>
  <w:LsdException Locked="false" Priority="62" SemiHidden="false"
   UnhideWhenUsed="false" Name="Light Grid Accent 6"/>
  <w:LsdException Locked="false" Priority="63" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium Shading 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="64" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium Shading 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="65" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium List 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="66" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium List 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="67" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium Grid 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="68" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium Grid 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="69" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium Grid 3 Accent 6"/>
  <w:LsdException Locked="false" Priority="70" SemiHidden="false"
   UnhideWhenUsed="false" Name="Dark List Accent 6"/>
  <w:LsdException Locked="false" Priority="71" SemiHidden="false"
   UnhideWhenUsed="false" Name="Colorful Shading Accent 6"/>
  <w:LsdException Locked="false" Priority="72" SemiHidden="false"
   UnhideWhenUsed="false" Name="Colorful List Accent 6"/>
  <w:LsdException Locked="false" Priority="73" SemiHidden="false"
   UnhideWhenUsed="false" Name="Colorful Grid Accent 6"/>
 </w:LatentStyles>
</xml><![endif]--></p>
<p class="MsoNormal">Text copied from MS Word with hidden code causing a white page in Laravel.&nbsp;</p>
```

### PR DESCRIPTION
**Pull request by MrCrayon**
`tinymce_init_callback` and `tinymce_setup_callback` can only be used effectively to set events or do something after tinyMCE has been initialized, to change init options tinymce currently needs to be initialized, destroyed and reinitialized with new settings.

This PR:
 - Exports default settings options
 - Moves initialization to `rich_text_box` blade file
 - Checks if custom options are set in BREAD details to merge
 - Enables different settings for each textarea
 - Adds documentation

**Warning**
If tinyMCE was used without calling `rich_text_box` partial it will need to be initialized:
```javascript
tinymce.init(window.voyagerTinyMCE.getConfig());
```

Closes #4551

### CODE REVIEW

**Comment by howdu** [comment]
Works well thanks - needed to re-compile via npm due to error: 
Cannot read property 'getConfig' of undefined. 

I tested by importing extra tinymce plugin into my  use of the voyager additional_js importing the extra tinymce plugin there which works well with your changes.

It would be great if tinymce/ace editors were not so tightly coupled into the main voyager app.js file and loaded separately when needed.

**Review by emptynick — CHANGES_REQUESTED** [review]
Couple things:

Lets move the documentation from `customization/tinymce.md` and merge them together with what you created.
You also need to add a link in `summary.md` to your new file.

Also it is not very clear to me where I have to put the `tinymceOptions`.

**Comment by MrCrayon** [comment]
tinymceOptions go in BREAD details, I should add that.
I'll check the other things too :+1:

**Comment by MrCrayon** [comment]
@emptynick I added a note to upgrade documentation, let me know if that's clear.

**Review by emptynick — APPROVED** [review]
Yep, that's better

**Pull request merged**
