### PR TITLE
Wrong fields alignemnt (padding) in create/edit form

### PR DESCRIPTION
**Pull request by reficul**
if you not pass "col-md-12" and if there are some custom display in other fields you have wrong alignment
schermata 2018-03-10 alle 13 23 08

### CODE REVIEW

**Comment by emptynick** [comment]
What about
`<div class="form-group col-md-{{ $display_options->width or 12 }}">`

**Review by fletch3555 — CHANGES_REQUESTED** [review]
I agree that @emptynick's suggestion is better.  @reficul, please update this PR to use his suggestion.

**Review by fletch3555 — APPROVED** [review]

**Comment by osc2nuke** [comment]
How i use that in the BREAD options?
`<div class="form-group col-md-{{ $display_options->width or 12 }}">`

Nevermind just figured it:
`{
    "display": {
        "width": 2
    }
}`

I could not find it in the docs, sorry!

**Comment by emptynick** [comment]
https://voyager.readme.io/docs/display-options

**Comment by osc2nuke** [comment]
Sigh.......... i really need to go for these glasses.

**Pull request merged**
