### PR TITLE
Allow action buttons to be filtered by row

### PR DESCRIPTION
**Pull request by leith**
The filter by data type is sometimes just not enough if you want conditions based on the row data

### CODE REVIEW

**Comment by fletch3555** [comment]
This is already possible with the authorization check (`@can()`) just above what you've changed.

**Comment by leith** [comment]
You are completely right, I just hadn't delved enough into creating policies. I'll close this and remove the branch.

It may be worth documenting this or providing an example - the only custom action in the project at the moment is the menu 'builder' button, but since that's is built into a custom view it doesn't go through the same BREAD pipeline where the default action buttons are rendered.

**Comment by MrCrayon** [comment]
Policies are not specific to Voyager it's standard Laravel, but you can see a custom one used for Posts in Voyager codebase.
https://github.com/the-control-group/voyager/blob/1.4/src/Policies/PostPolicy.php

**Comment by leith** [comment]
@MrCrayon absolutely, policies are a far broader-use thing in Laravel, I was more meaning the use of them when restricting custom Action buttons.

The example `PostPolicy` is used with the "standard" read/edit/delete rather than anything custom. Additional documentation is probably more useful than the example in this case - it's not especially clear that the `getPolicy()` method is for defining the *permission* (for the `@can` call) to look up on the Policy file, and the policy is determined by association on the DataType (so need to look at the `PostsSeeder` from the current example). The `shouldActionDisplayOnDataType()` documents how to filter new action buttons so they only appear for certain data types, which is good.

**Pull request closed without merging**
