### PR TITLE
 fix: package.json to reduce vulnerabilities 

### PR DESCRIPTION
**Pull request by x1mdev**
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/npm:bootstrap:20160627

Latest report for x1mdev/voyager:package.json:
https://snyk.io/test/github/x1mdev/voyager?targetFile=package.json

### CODE REVIEW

**Comment by emptynick** [comment]
You cant just replace Bootstrap 3 with 4.
This will blow up our design.

**Comment by x1mdev** [comment]
@emptynick I see.. let me check for some other possibilities.

**Comment by emptynick** [comment]
It says it was fixed in `3.4.0` but I doubt that there is such a version.
The only way is to upgrade to `4.0.x` but this requires a lot of work

**Comment by marktopper** [comment]
Updating to bootstrap `v4.0.x` requires more work than this.

**Pull request closed without merging**
