### PR TITLE
Add Vietnamese Language

### PR DESCRIPTION
**Pull request by hnphi**
Add Vietnamese Language

### CODE REVIEW

**Comment by emptynick** [comment]
Are you planning to translate the rest also?

**Comment by hnphi** [comment]
> Are you planning to translate the rest also?

Yes, I am. Present, I'm translated important parts first, but I'll complete all translate.

**Comment by emptynick** [comment]
Let me know when you are done so we can merge this in then.

**Comment by MrCrayon** [comment]
Author is probably busy but I think a partial translation is still good and other people can contribute once merged.
@emptynick @fletch3555  What do you think?

**Review by MrCrayon — APPROVED** [review]
:+1:

**Pull request merged**
