### PR TITLE
Remove unnecessary relationship-code

### PR DESCRIPTION
**Pull request by emptynick**
Method `getRelationships` in `BreadRelationshipParse` and the whole `HasRelationship` Trait relies on relationship-method-names which we dont use/know.
Therefore it is not usable/useful and I removed it completely.
Because of that `relationToLink()` doesn't do anything also and I removed everything related to it.

Sideeffect: `$with` in models is working again.
Fixes https://github.com/the-control-group/voyager/issues/3604 and fixes https://github.com/the-control-group/voyager/issues/2561

### CODE REVIEW

**Comment by DrudgeRajen** [comment]
> $with in models is working again. 

Can anybody explain ?

**Comment by abhinav-rabbit** [comment]
@emptynick **I think this is just code clean up**. This PR just remove all the remaining code related to relationship with the use of Eager loading capabilities, which was not working (which had been deprecated i guess).

As I had stated it the comment is the issue:
https://github.com/the-control-group/voyager/issues/3604#issuecomment-427711651
**"We have data in $item->type as 'relationship', but in $details->type we have value as 'belongsTo'."**

This PR removes feature related to eager loading of the relation once and for all. 

@DrudgeRajen "$with in Model" will not work for sure, Since we don't have any relationship defined on Model level and cant be eager loaded in any was possible.

**Comment by ntuple** [comment]
@emptynick **I think this is just code clean up**. This PR just remove all the remaining code related to the relationship with the use of Eager loading capabilities, which was not working (which had been deprecated I guess).

As I had stated it the comment is the issue:
https://github.com/the-control-group/voyager/issues/3604#issuecomment-427711651
**"We have data in $item->type as 'relationship', but in $details->type we have value as 'belongsTo'."**

This PR removes feature related to eager loading of the relationship once and for all. 

@DrudgeRajen "$with in Model" will not work for sure, Since we don't have any relationship defined on the Model level and cant be Eager loaded in any way possible.

**Comment by emptynick** [comment]
> This PR removes feature related to eager loading of the relationship once and for all.  

Because all those features solely rely on relationship-method names. So it can't and will never work with the way we currently define relationships. Why keep it then?!

> @DrudgeRajen "$with in Model" will not work for sure, Since we don't have any relationship defined on the Model level and cant be Eager loaded in any way possible.  

If you define `$with` in your model it will work again. I can guarantee you that.
See issue #2561

**Comment by DrudgeRajen** [comment]
@emptynick I understand `$with` will work but what if dev will not keep `protected $with=['methodname'] `? Eager Load will not work ? I think the method that are removed were  somehow handling these things, might be in older version.

**Comment by emptynick** [comment]
`$with` is a feature of Laravel/Eloquent.
And because we query relationships directly through the foreign model (not through the method) we don't need to eager-load the relationship before.

**Review by fletch3555 — APPROVED** [review]

**Comment by yueyanzhao** [comment]
when updated to v1.1.11, 
in my project,there is a error,
"Method App\Http\Controllers\Voyager\CouponController::getRelationships does not exist.",
I only composer update, what I need to do

**Comment by yueyanzhao** [comment]
@emptynick

**Comment by yueyanzhao** [comment]
@emptynick

**Comment by yueyanzhao** [comment]
@emptynick 
when updated to v1.1.11,
in my project,there is an error,
"Method App\Http\Controllers\Voyager\CouponController::getRelationships does not exist.",
I only composer update, what I need to do after this update? 
waiting for your reply, thank you!

**Comment by emptynick** [comment]
Just remove the method call. It's unnecessary

**Comment by yueyanzhao** [comment]
@emptynick ok, thank you

**Pull request merged**
